<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create ticket</name>
   <tag></tag>
   <elementGuidId>7f89faa6-57c4-483f-af96-a57aef629cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Create20ticket']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Create20ticket</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a9c532c-7ce7-4de1-ac4b-4f41440df512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>c8907dbe-bf4b-4ded-ac16-2e7d8f8924d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Create20ticket</value>
      <webElementGuid>4a502411-cf56-4d64-8d06-c861adecca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addNewTicket();</value>
      <webElementGuid>09b57a71-3d84-486b-b060-d2307358db83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create ticket</value>
      <webElementGuid>a8427380-7f24-48e2-a530-db0b3de1fa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Create20ticket&quot;)</value>
      <webElementGuid>4b0bcab6-0d3c-4825-973a-b69b4d24743b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSTickets/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>0b93fefa-96b7-4ca2-b4f0-359a6ddc91b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Create20ticket']</value>
      <webElementGuid>340dc78c-e5fb-4630-bf1b-6581423efe76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageData']/div[4]/div/div[2]/ul/li/a</value>
      <webElementGuid>5e66b1c3-78b9-4fbe-89e1-26a76be4f56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create ticket')]</value>
      <webElementGuid>41043ec8-c823-4595-a85b-e0d8af53e5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[1]/following::a[1]</value>
      <webElementGuid>0312c6d6-81a1-49de-b16c-41b96415ecf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::a[1]</value>
      <webElementGuid>c74896a6-4f9c-4d86-a398-becfce01d24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver: 10.10.04'])[1]/preceding::a[2]</value>
      <webElementGuid>c0505f1c-c116-47a3-b13b-fac72d3b21b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of services'])[1]/preceding::a[3]</value>
      <webElementGuid>838d196e-4a91-4e2f-8dc1-ec8f4df3c38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create ticket']/parent::*</value>
      <webElementGuid>83f028b0-3b82-4ca2-a0ec-c5a5b4a87c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>99a52e14-3f9f-4b6c-9512-104597c6e917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Create20ticket' and (text() = 'Create ticket' or . = 'Create ticket')]</value>
      <webElementGuid>02495e3d-6594-465a-9f30-ce316a7e86fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
