<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My tickets</name>
   <tag></tag>
   <elementGuidId>6e84fe40-9617-49ea-a750-82920b907a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div[2]/div[4]/div[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:void(0);' and @id = 'secondary_link_manageHelpDesk' and @onclick = concat(&quot;encryptURLForPanel(&quot; , &quot;'&quot; , &quot;runet.do?activity=submit&amp;mod=MyTicketHelpDesk&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'My tickets' or . = 'My tickets') and @ref_element = 'Object Repository/Empxtrack_SSTickets/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_manageHelpDesk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d2de278-68fd-462c-88a1-11161fc4eb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>b9f311b5-043e-414a-9c22-673d476fb6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_manageHelpDesk</value>
      <webElementGuid>d07f14b5-92e9-4ff8-85fa-2e09fb77b0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('runet.do?activity=submit&amp;mod=MyTicketHelpDesk')</value>
      <webElementGuid>cb1b7ff6-3bc0-4373-abb0-dbc48b24eec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>07389866-f32d-4fc3-9ca1-736ca4a9616e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My tickets</value>
      <webElementGuid>acd2de6d-5086-4988-95a4-089694001ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_manageHelpDesk&quot;)</value>
      <webElementGuid>9ff42ae3-7dd8-4cf1-a801-37a3a41f4749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSTickets/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>3c4a199c-9bc1-4437-903a-89143c70770c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_manageHelpDesk']</value>
      <webElementGuid>e54b6cd8-cf30-4d2e-bee3-cac03cd4fb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showMyTicketsHelpDesk_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>8e7dccfb-2418-42e6-941e-0f55c58cd963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My tickets')]</value>
      <webElementGuid>894283de-385e-4fea-8907-ffe90001bc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[2]/following::a[1]</value>
      <webElementGuid>edb21175-4845-4a29-b53d-68663d36eb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[2]/following::a[1]</value>
      <webElementGuid>eb44e571-a986-4148-8d13-7a7374fdb069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create ticket'])[1]/preceding::a[1]</value>
      <webElementGuid>8fd6c6ce-6654-4148-88dd-261e30fc8c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver: 10.10.04'])[1]/preceding::a[3]</value>
      <webElementGuid>2090a20d-04d8-4f05-bf04-24da52512739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My tickets']/parent::*</value>
      <webElementGuid>4cf289f1-1abb-4ede-b5b4-217b92815cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>ddcac1ef-9d8d-46d2-9bb5-4ccd11343916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[4]/div[2]/a</value>
      <webElementGuid>e2d7d96e-7cb7-4281-b51a-e90ae811dfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_manageHelpDesk' and (text() = 'My tickets' or . = 'My tickets')]</value>
      <webElementGuid>6cb4f945-12e8-461c-82e3-88bc2a44d206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
