<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Request has been submitted successfully</name>
   <tag></tag>
   <elementGuidId>465ac84d-2d38-492c-9e70-193f2fb7ea93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snackbar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#snackbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>900ea7d3-aa93-4807-a175-2b89cc31dd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snackbar</value>
      <webElementGuid>ef96c486-262f-473e-8fb9-b95380a69a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>showSnackbar</value>
      <webElementGuid>46f563fa-e130-41bb-8a71-eb28589f6617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request has been submitted successfully.</value>
      <webElementGuid>7d466000-f4db-4b05-ab78-813da90686ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snackbar&quot;)</value>
      <webElementGuid>bebdb12d-1d33-43ff-b0d6-af210373a9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSTickets/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>c3d60981-3f55-42c5-853b-c901d9c0ae22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='snackbar']</value>
      <webElementGuid>0880e4c6-cc55-4ca7-b03d-53ca14e4e760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy policy'])[1]/following::div[15]</value>
      <webElementGuid>63258dac-9e01-4dc7-a404-9a7cab470c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of services'])[1]/following::div[15]</value>
      <webElementGuid>132bc8f5-a474-4fe2-92e1-4a8fd3fdafbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::div[2]</value>
      <webElementGuid>784fe5b2-b283-4195-b96e-da8b702a4434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[5]</value>
      <webElementGuid>1117f283-ff7b-46f9-b9ce-d7fec6c320c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'snackbar' and (text() = 'Request has been submitted successfully.' or . = 'Request has been submitted successfully.')]</value>
      <webElementGuid>6b36d00a-7624-4c5c-b5d5-4adc3fcc6307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
