<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My ticketsHelp</name>
   <tag></tag>
   <elementGuidId>a927788d-2bee-48b6-9780-581a5c0447a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show_hide_page_title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#show_hide_page_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89471df9-3435-4240-a8bf-31bc51fe7448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 headerbar</value>
      <webElementGuid>f3635ec9-c774-417b-8a00-8bf37c8514f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_hide_page_title</value>
      <webElementGuid>0e875bcc-2f02-4124-8664-8164fe63d66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My tickets  Help×</value>
      <webElementGuid>155c93e2-2d59-4a98-9541-c508c3389b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_hide_page_title&quot;)</value>
      <webElementGuid>d3bcd895-8273-4bdd-997c-791156730763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='show_hide_page_title']</value>
      <webElementGuid>3ac201da-8cc5-420d-ae9a-4a138c435f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/div</value>
      <webElementGuid>c438440b-8c9e-439f-bb9b-2143d4c10d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::div[8]</value>
      <webElementGuid>71414280-1af7-470c-873b-7d44bb9d1eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[11]</value>
      <webElementGuid>b54ebdd5-f7d2-46bc-bfc2-9dc5577c9bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div</value>
      <webElementGuid>68bd43d6-fad5-478a-878f-ba1e9d30d390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'show_hide_page_title' and (text() = 'My tickets  Help×' or . = 'My tickets  Help×')]</value>
      <webElementGuid>d6be758b-597d-4ce6-a72f-ab472acc480d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
