<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OR__selectedSearchOnTicketId</name>
   <tag></tag>
   <elementGuidId>2bcdc061-3d8e-4a72-b404-8cf6cf78c2af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_selectedSearchOnTicketId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_selectedSearchOnTicketId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8da19f6-ec2b-4eb5-ab35-6e2fed3e995b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_selectedSearchOnTicketId</value>
      <webElementGuid>81a87031-d9f9-4415-aeab-dbbc2a8f75bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29bfbed8-992a-4721-9857-0abd699dedab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61d77a47-d5e2-4e0e-8c98-1916682ff72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search on ticket id</value>
      <webElementGuid>ac2cccd4-3aef-4f1a-af89-b8da1771d4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>943b1598-3746-4f10-8fae-21a550247a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_selectedSearchOnTicketId&quot;)</value>
      <webElementGuid>3a2bd787-910d-4cad-902d-8135e1f4bc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSTickets/Page_Home page/iframe_Self services_homePageFrame (4)</value>
      <webElementGuid>a9d3ddc8-e451-4d58-a88b-f05e3622571a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_selectedSearchOnTicketId']</value>
      <webElementGuid>28067845-aa68-4b84-8358-b9c5c934d74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_filtersOnTicket']/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>fab26c20-9b7d-48e2-836d-544b6f75a358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>77fa10b0-4741-4a30-b595-1cb60b938f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_selectedSearchOnTicketId' and @type = 'text' and @placeholder = 'Search on ticket id']</value>
      <webElementGuid>bddd79de-44d8-40d5-aec6-2ac27c2254b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
