<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0900</name>
   <tag></tag>
   <elementGuidId>93223181-704d-4bb5-9cf9-fe3f33c1f49b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='startTime_09:00']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dcae3fd-d70b-442e-8c7d-c80fc2fd17e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timeslot_li_frame</value>
      <webElementGuid>2ae4090f-6ced-44df-9142-f2f503d1ecf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startTime_09:00</value>
      <webElementGuid>a2fdc3dc-c543-49cc-867b-364f5c1d9f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:updateTimeslot(this.id);return false;</value>
      <webElementGuid>12f41844-b97a-4cea-bc14-e06fbcade136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>09:00</value>
      <webElementGuid>b6953726-df00-4e8f-ab20-654bfaede82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startTime_09:00&quot;)</value>
      <webElementGuid>2ade8ae3-d548-4524-b673-d5b1251ec4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>11604162-8cc2-490d-b643-b650fce643d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='startTime_09:00']</value>
      <webElementGuid>e6371d48-b465-451f-86d6-93c31799acea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[6]/div/div[19]</value>
      <webElementGuid>fb10af35-14e0-4d8e-873c-8edaf4b99f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date'])[1]/preceding::div[6]</value>
      <webElementGuid>53635e85-63ec-4933-adfa-1d2533c22faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start time'])[1]/preceding::div[8]</value>
      <webElementGuid>9eb8140b-fe80-49b2-bf22-0044a0e89480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='09:00']/parent::*</value>
      <webElementGuid>c888cf49-9c8b-4cc4-b0f7-a78d13bf880b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[19]</value>
      <webElementGuid>08c4d656-fc47-4a49-876e-c5243d7eaa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'startTime_09:00' and (text() = '09:00' or . = '09:00')]</value>
      <webElementGuid>9288b6ff-cfc5-4968-a082-9435c19660a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
