<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Confirmation</name>
   <tag></tag>
   <elementGuidId>223a07b0-60ad-4c7f-a23f-64520624dd65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bootstrap-dialog-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='96110984-99a4-49ac-89c5-255af1631a8a']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7d75ef2e-3720-4b1d-b515-28d5af5c2988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootstrap-dialog-header</value>
      <webElementGuid>a5ae3e48-12b1-4ebe-8617-45dfa36cc17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Confirmation!</value>
      <webElementGuid>5226b932-124b-42ac-b69c-7e761ffd7ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;96110984-99a4-49ac-89c5-255af1631a8a&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header bootstrap-dialog-draggable&quot;]/div[@class=&quot;bootstrap-dialog-header&quot;]</value>
      <webElementGuid>30aa5b82-cf19-48b0-8c30-cf38ae826eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Event/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>460fc0ed-53be-4bfe-825a-d32d520b177e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='96110984-99a4-49ac-89c5-255af1631a8a']/div/div/div/div</value>
      <webElementGuid>57c4e5a1-62d5-455a-ac7e-c93f1e8ede5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::div[23]</value>
      <webElementGuid>6ab7b5e3-1a5e-4327-b59b-73f4814b81d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press ALT 0 for help'])[1]/following::div[40]</value>
      <webElementGuid>9f8d2d87-8c10-49c9-93ea-cd88a86294b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div</value>
      <webElementGuid>0ee552c0-7924-46c0-8bef-8702e3bed1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×Confirmation!' or . = '×Confirmation!')]</value>
      <webElementGuid>3a3b566f-a291-4b25-8547-9ba5fcb262fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
