<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start date_date_selectedStartDate</name>
   <tag></tag>
   <elementGuidId>7aa5c99c-af2a-4ce1-a703-8bf48cb0e725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27c4646f-74d3-4883-b08f-fdeafca936e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23c9a83e-7a9e-4be0-aa7f-0dba511a61cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedStartDate</value>
      <webElementGuid>c79677f0-80a8-4f0a-8a68-d7c9737481f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>28/01/2024</value>
      <webElementGuid>cab2e5a9-d75e-4e2c-bed1-45848ccc4e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_selectedStartDate</value>
      <webElementGuid>fb84eef9-d76b-4f82-a898-0c09bd7353d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>b304152b-fea3-4606-a002-f5fb8668950e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedStartDate&quot;)</value>
      <webElementGuid>782a7649-2ec6-49ee-8e47-79c233b3e968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>c78340e8-e56d-451d-a86b-8f333cebfb87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedStartDate']</value>
      <webElementGuid>ccb2a37a-560f-427c-bf81-b1b29fbff27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[7]/div/input</value>
      <webElementGuid>89e727d0-c16f-45dd-94ba-02e03a9fd57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[7]/div/input</value>
      <webElementGuid>8bb91622-4d82-4682-b8df-6ea9b0230787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectedStartDate' and @name = 'date_selectedStartDate']</value>
      <webElementGuid>796ecc84-884c-41a0-b257-dfe1555ce861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
