<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location_location</name>
   <tag></tag>
   <elementGuidId>acf2d475-68d0-485b-a715-12986b927246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88814e62-922e-4def-93f5-33775539969c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1c43e70-3f11-4468-a00b-26c48dbf719d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>e5bf25fa-4a75-4e9b-83b6-a7a32c490c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f2631332-90db-401d-abab-6cf7a2260ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
      <webElementGuid>e455204d-7f41-4584-ab53-b22845540e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>8b9713a5-bcb5-45f2-9bf0-360d9cebc8e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location']</value>
      <webElementGuid>8e8f548c-27ea-45ec-84d5-25443098e213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[3]/div/input</value>
      <webElementGuid>01cc1c22-d47a-4186-9f4d-a2ad0cc733ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/input</value>
      <webElementGuid>1a2c95ce-58db-45cb-bbe4-3d9f70b1db79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'location']</value>
      <webElementGuid>488224b5-5ec6-4f3d-ad40-ead9867402dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
