<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TimeZone</name>
   <tag></tag>
   <elementGuidId>4ba8f2af-ca4a-4d84-8a71-fca3f3e7d0d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timeZone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'timeZone' and (text() = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' or . = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f08885db-c94a-4d67-8b30-c558cc96cc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeZone</value>
      <webElementGuid>b9cdb4cf-1d79-4625-aa22-63eb1509d09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dadc6254-99a0-4404-9d1c-46a83cefb96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</value>
      <webElementGuid>4e9a4248-8b24-4125-aa54-90aa443938ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeZone&quot;)</value>
      <webElementGuid>d9fdcbc4-a855-4a4c-bfce-4f01d9bc9c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>8b5f9a8b-93a9-4ea4-bcd8-898f2de4b61a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='timeZone']</value>
      <webElementGuid>8762df08-806d-41e4-a05f-cc9803b571b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[13]/div/select</value>
      <webElementGuid>4c61f708-a72e-4b5c-8e27-bf20009d35c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/following::select[1]</value>
      <webElementGuid>a41148f5-0e0c-4b48-9a82-afcd6fa21aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[2]</value>
      <webElementGuid>356dd9ea-f9e7-4d6d-b49c-6c20b17866bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/preceding::select[1]</value>
      <webElementGuid>54498727-ca3f-4458-82f0-086e78713215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/select</value>
      <webElementGuid>6a690d51-514e-424a-9125-35b016a62502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'timeZone' and (text() = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' or . = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi')]</value>
      <webElementGuid>565a4583-61c9-427d-a081-e6060c48df90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
