<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Duration</name>
   <tag></tag>
   <elementGuidId>a3bac8a1-efd2-4aa5-852b-3c496c89d3bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>401ac5b1-1d9b-4acd-ab77-933e13add2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>4aab8f7c-3b31-4316-b058-67f927888745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>681b068f-3fd8-4a2f-b0e7-2960e661a43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour</value>
      <webElementGuid>37925db0-46e4-40f0-aa72-380e4913a1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;duration&quot;)</value>
      <webElementGuid>6443b712-1c99-4bd8-8cb3-343eb2595e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>52060cc0-ec8d-41af-a59e-f1fc167e41af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='duration']</value>
      <webElementGuid>6e0aaff5-f017-429a-895b-7511fbeea623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationDiv']/div/select</value>
      <webElementGuid>e8b2514c-4f05-4a62-b5ca-cda922bb62d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[1]</value>
      <webElementGuid>87c7189a-2654-4177-9a48-da09834c8aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End time'])[1]/following::select[2]</value>
      <webElementGuid>1c6dd2f4-c149-44b7-8930-547cdcbdddd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/preceding::select[1]</value>
      <webElementGuid>84114ab1-e478-430a-8007-18542dcab81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/select</value>
      <webElementGuid>9f2c14d8-4470-47dc-af84-027dc32e417a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'duration' and (text() = '---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour' or . = '---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour')]</value>
      <webElementGuid>96ed6ea1-cda0-4075-b56a-df5fb92c76ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
