<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  10</name>
   <tag></tag>
   <elementGuidId>a3d0e99f-6d2a-4a12-b8c0-c911cf43409a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank&quot;)[count(. | //div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank' and @class = 'optionDivSelected' and (text() = 'View details for: emp  10 ' or . = 'View details for: emp  10 ')]) = count(//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank' and @class = 'optionDivSelected' and (text() = 'View details for: emp  10 ' or . = 'View details for: emp  10 ')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bed346b-fac9-4eba-9d65-185f8dd272d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank</value>
      <webElementGuid>6a3e7a8a-7386-4f5d-8dad-f23a99a01fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>5793e58b-a463-4b16-8a50-683776444123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  10 </value>
      <webElementGuid>3c7b7935-1f2c-4ff0-9ffa-514b3996b3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank&quot;)</value>
      <webElementGuid>52b34094-0be7-45e5-bace-6652a3e59d24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank']</value>
      <webElementGuid>7981bc16-dc79-45a2-9b73-9a715d87b84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[10]</value>
      <webElementGuid>57334f2d-2afe-4d23-87e3-c7838a09ab6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>350d7b6f-d39f-4d48-a2f1-037ce9f7742e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>da20bf08-db6d-4c4a-9e18-fdd560b62e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]</value>
      <webElementGuid>dd9f2bb8-e532-466e-83e8-177a72315a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEh0hSG+EZASBP33JnqGX4w4FSucEcm60J4KPY4v8ZYO5vb5lqC5qyw%2FkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOj2DPcT4H6s%2F$$panel$$_blank' and (text() = 'View details for: emp  10 ' or . = 'View details for: emp  10 ')]</value>
      <webElementGuid>3795f6f0-70ef-4f60-8559-78875233515f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
