<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My attendance dashboard</name>
   <tag></tag>
   <elementGuidId>e53400c3-7278-4b5e-9b09-50175ce4b593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;mod=MyAttendance$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0c1c2e8-54cd-4d88-853d-e4c8d8dcea40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;mod=MyAttendance$$panel$$_blank</value>
      <webElementGuid>0d5629bc-67bf-419d-80cc-b4f035fd3034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>cc84f81f-c458-421c-b758-09e55e9802f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My attendance dashboard</value>
      <webElementGuid>54473444-a00d-435e-b8c5-c21fad6ec294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;mod=MyAttendance$$panel$$_blank&quot;)</value>
      <webElementGuid>426e86f2-4321-4200-b7ea-a3b7bf1aa5b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;mod=MyAttendance$$panel$$_blank']</value>
      <webElementGuid>8ab48471-2377-417e-8795-264db474d545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>11fe0adb-22cf-44fa-b85f-5d088fac4605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/following::div[2]</value>
      <webElementGuid>c6710d7c-d4d5-4f39-aec8-bacd744e3c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::div[10]</value>
      <webElementGuid>bcc7da8c-66ba-4286-899d-ec14c5c1fc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services dashboards'])[1]/preceding::div[1]</value>
      <webElementGuid>48fc07fd-4aa8-4563-95df-ef8f3707fc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>7bdfdeea-0446-485c-bbab-866b55af3f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My attendance dashboard']/parent::*</value>
      <webElementGuid>ceebf7c0-2154-4404-b603-5ca20447e24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>157cb09b-1556-48cb-a22b-80296dced585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;mod=MyAttendance$$panel$$_blank' and (text() = 'My attendance dashboard' or . = 'My attendance dashboard')]</value>
      <webElementGuid>9c95c320-e98b-4523-9952-6c0df226cf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
