<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  01</name>
   <tag></tag>
   <elementGuidId>402468c6-aa24-4e1c-832f-f6a52846b560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank&quot;)[count(. | //*[@class = 'optionDivSelected']) = count(//*[@class = 'optionDivSelected'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5e34d84-d7d2-43cc-8773-7ec939b59d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank</value>
      <webElementGuid>e7504df7-e55e-4231-9c12-3eace4e17500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>26fdc2d0-a588-4ff6-88bb-3bd4bdec2b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  01 </value>
      <webElementGuid>cc7de5c4-975e-4fa9-b996-1db8b106a060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank&quot;)</value>
      <webElementGuid>0f8255d5-2bc6-4349-91df-295e7618de98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank']</value>
      <webElementGuid>abee36b0-49b7-4074-a8a0-3183be384c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>166378f3-63c3-4a56-807c-e0a7656ab40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/following::div[2]</value>
      <webElementGuid>bd07e528-012d-4b5c-b208-268711aee03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::div[10]</value>
      <webElementGuid>5ec456cd-4d00-4c10-a91e-bb8a641967e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>4f19edf9-1473-4d13-a6d9-e75e040ea800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank' and (text() = 'View details for: emp  01 ' or . = 'View details for: emp  01 ')]</value>
      <webElementGuid>9e276552-ed3d-4762-bd69-d00677c251fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
