<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AttendanceHelp</name>
   <tag></tag>
   <elementGuidId>15803380-1a22-4c60-ad13-dc2c5597bfc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='display_page_title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#display_page_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>edef8cdf-69e0-458d-a276-d07d5951f159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_page_title</value>
      <webElementGuid>fdf1c7f9-9a2f-4a4c-bcce-6dfc5648b97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attendance  Help</value>
      <webElementGuid>d2b1bb8f-7db2-4937-b6f0-91db856ee595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_page_title&quot;)</value>
      <webElementGuid>ec48dd43-a8dc-45b2-9afe-93eb23f811af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='display_page_title']</value>
      <webElementGuid>d29a8a3d-9c8a-4698-b5ea-e9fab254bfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_hide_page_title']/div/div</value>
      <webElementGuid>6631b437-108a-4ef1-8dff-4d23201d6ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::div[10]</value>
      <webElementGuid>d55e1bd4-6005-4a9c-9a4b-6700b0726d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[13]</value>
      <webElementGuid>578e3cad-6c57-4935-b1bc-d29174f16ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::div[5]</value>
      <webElementGuid>d3c312cd-a04d-417d-98c0-ad2be29817c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div</value>
      <webElementGuid>4264bdc9-a669-434e-9f80-490c0065119d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'display_page_title' and (text() = 'Attendance  Help' or . = 'Attendance  Help')]</value>
      <webElementGuid>de42a13e-7728-4da2-b1be-7b30ce55805b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
