<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Self services dashboards</name>
   <tag></tag>
   <elementGuidId>d650d7ea-f914-4580-9305-f22ec470dcfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='/empxtrack/runet.do?activity=submit&amp;mod=transact&amp;selMenuItemChoice=transact$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97a3098b-8a7f-4306-8a57-306e4d4f3a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>/empxtrack/runet.do?activity=submit&amp;mod=transact&amp;selMenuItemChoice=transact$$panel$$_blank</value>
      <webElementGuid>a171ee3d-a665-4d33-8c44-72e4a9feda8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>18f17b79-2c43-46fc-93d5-581f49229ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self services dashboards</value>
      <webElementGuid>25c37942-b1d7-4624-80fe-b78cd3e687c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/empxtrack/runet.do?activity=submit&amp;mod=transact&amp;selMenuItemChoice=transact$$panel$$_blank&quot;)</value>
      <webElementGuid>b92691b8-5d9d-4ab5-97bc-0449c78f7b3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='/empxtrack/runet.do?activity=submit&amp;mod=transact&amp;selMenuItemChoice=transact$$panel$$_blank']</value>
      <webElementGuid>092b7471-0801-4af8-9acb-6261f403aea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[2]</value>
      <webElementGuid>a4f7c85d-3d39-4571-afb6-1232bfe8c6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My attendance dashboard'])[1]/following::div[1]</value>
      <webElementGuid>eaf666f7-45c9-40af-bc0f-30a2487275da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/following::div[3]</value>
      <webElementGuid>de51a877-3aee-4e67-acf5-6e936c76bb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>073da223-4397-4215-a0d1-7acc7e900594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>c7ba225f-982d-4e21-b1c5-8156b66fcab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Self services dashboards']/parent::*</value>
      <webElementGuid>6868a2a4-ac47-4985-8e5f-96172029209c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]</value>
      <webElementGuid>4635442f-498b-431f-947b-212d7108d28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '/empxtrack/runet.do?activity=submit&amp;mod=transact&amp;selMenuItemChoice=transact$$panel$$_blank' and (text() = 'Self services dashboards' or . = 'Self services dashboards')]</value>
      <webElementGuid>cb059cff-9408-4cc1-b906-a941ea5c8a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
