<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_moduleName</name>
   <tag></tag>
   <elementGuidId>ac62dfb1-b74d-42da-b38b-83662511beff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='moduleNameId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#moduleNameId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c009a534-daaa-4492-ac4a-9490af501bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moduleName</value>
      <webElementGuid>a18a47c5-1289-4ea4-ad47-38e5c8b0f28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>84px</value>
      <webElementGuid>dc88637f-61ae-4fed-994e-d52c2670e78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-logobar form-control </value>
      <webElementGuid>9243180b-9af9-4eb0-95bd-938e180fd7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ajax_showOptions(this, 'getEmployeesByLetters', event, 'advancedFeatureSearch')</value>
      <webElementGuid>4af36bb1-93c2-42ef-982b-dc4b41b6d107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c411da77-53bf-4b81-964d-fd4c0d8bc91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moduleNameId</value>
      <webElementGuid>7b5c83c7-3122-44f5-b25c-3f8de4add9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d4f74ad-5930-45c4-b676-131dff082ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a feature or employee name (@name)</value>
      <webElementGuid>7a66c3a8-0a89-4015-8dcc-5cf17c6456f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleNameId&quot;)</value>
      <webElementGuid>8247dbde-b74c-409d-8387-d288d4e2c356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='moduleNameId']</value>
      <webElementGuid>0556b856-82de-4e7b-bd14-363f66211dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cd-primary-nav']/li/div/div/input</value>
      <webElementGuid>d3d30092-f689-4aef-a172-46a09aa6f355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/input</value>
      <webElementGuid>afb3469d-df52-4ff2-bddc-4628e7483dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'moduleName' and @id = 'moduleNameId' and @type = 'text' and @placeholder = 'Search a feature or employee name (@name)']</value>
      <webElementGuid>13a9fb38-81b5-43e6-8545-aef2643e563d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
