<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The login credentials are not correct. Please contact your HR Manager or Administrator for support</name>
   <tag></tag>
   <elementGuidId>4ba2d069-bd63-4f6d-8709-d6534bdd88ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m99']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m99</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08bb97b0-a430-49e8-b7f2-0cea26b010fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>err</value>
      <webElementGuid>ee942f3f-d836-485a-8873-504e8f71d036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m99</value>
      <webElementGuid>373dcc43-ed70-4a71-bfde-0c00916a91f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The login credentials are not correct. Please contact your HR Manager or Administrator for support.</value>
      <webElementGuid>028af44b-f2c8-4b91-a2ec-4db6d622a0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m99&quot;)</value>
      <webElementGuid>1764b88a-b3ea-45d9-92b1-9cf83854ab61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='m99']</value>
      <webElementGuid>988e3f9c-4016-4546-86b1-fe2bab71ea58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Should be checked if you are on a public computer.)'])[1]/preceding::div[2]</value>
      <webElementGuid>07fa0053-ba98-4b24-8eea-d3550f517b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The login credentials are not correct. Please contact your HR Manager or Administrator for support.']/parent::*</value>
      <webElementGuid>f2a93611-2046-4397-b8b0-06bd1d9ea8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div</value>
      <webElementGuid>10d24bf6-d63d-4809-a0b2-3669e47017be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'm99' and (text() = 'The login credentials are not correct. Please contact your HR Manager or Administrator for support.' or . = 'The login credentials are not correct. Please contact your HR Manager or Administrator for support.')]</value>
      <webElementGuid>2aff05f5-8ada-43ab-9922-399f5a20a25e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
