<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_End day</name>
   <tag></tag>
   <elementGuidId>d790ca40-19b4-42c4-b6f4-7860fc11cdff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.attendance-widget-endbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;confirmToEndDayOnHomePage('30/01/2024','1002498','E');return false;&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @onclick = concat(&quot;confirmToEndDayOnHomePage(&quot; , &quot;'&quot; , &quot;30/01/2024&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1002498&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;E&quot; , &quot;'&quot; , &quot;);return false;&quot;) and @alt = 'End day' and (text() = ' End day  ' or . = ' End day  ') and @ref_element = 'Object Repository/Empxtrack_DashAttendance/Page_Home page/iframe_Self services_homePageFrame (4)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>082e4847-0882-4533-91b6-74ae0628e034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e35745d5-8a89-4fdc-b7c2-de6bfa529b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>confirmToEndDayOnHomePage('30/01/2024','1002498','E');return false;</value>
      <webElementGuid>70802cbf-0211-4309-876b-f2126904639d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>End day</value>
      <webElementGuid>edb0cf44-d68b-4580-95b8-e16c0cca2579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attendance-widget-endbtn</value>
      <webElementGuid>8ce135ea-d5d9-4f7a-b830-3a5214f3da78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> End day  </value>
      <webElementGuid>d25b54dc-586e-4409-8b2e-64d3ca4cba05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendance_content&quot;)/a[@class=&quot;attendance-widget-endbtn&quot;]</value>
      <webElementGuid>02a49df5-3f1b-4563-ad6d-704f4b53cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashAttendance/Page_Home page/iframe_Self services_homePageFrame (4)</value>
      <webElementGuid>73d1a4e5-2ff9-4c51-9bdc-d626e27794a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;confirmToEndDayOnHomePage('30/01/2024','1002498','E');return false;&quot;]</value>
      <webElementGuid>b59fa92b-5424-4c4e-ab7b-cb8b5dac30d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attendance_content']/a[2]</value>
      <webElementGuid>d09f30bf-b66f-4d5e-a82f-5df48576fd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total hours'])[1]/following::a[2]</value>
      <webElementGuid>689ee8fb-c052-4297-ab34-d4dd37429beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>dd9972c6-0c74-44c0-aa84-a6916c1daeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>b5060267-2c94-431c-8025-3f915ecf9feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a[2]</value>
      <webElementGuid>68eb6093-168f-4634-82f3-2db46e4948f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @alt = 'End day' and (text() = ' End day  ' or . = ' End day  ')]</value>
      <webElementGuid>5b3a9e3c-1843-441b-bdf9-c838e17b7870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
