<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Resume work</name>
   <tag></tag>
   <elementGuidId>215cd6a0-1104-4b7b-97d0-37c5841004ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.attendance-widget-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;markTodayAttendanceOnHomepage('30/01/2024','1002498','R');return false;&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @onclick = concat(&quot;markTodayAttendanceOnHomepage(&quot; , &quot;'&quot; , &quot;30/01/2024&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1002498&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;R&quot; , &quot;'&quot; , &quot;);return false;&quot;) and (text() = ' Resume work   ' or . = ' Resume work   ') and @ref_element = 'Object Repository/Empxtrack_DashAttendance/Page_Home page/iframe_Self services_homePageFrame (3)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59adc332-673c-43d0-befa-72300ba6fdb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>00f9e804-fc3f-4b41-8969-428d1c51871b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>markTodayAttendanceOnHomepage('30/01/2024','1002498','R');return false;</value>
      <webElementGuid>48ebac56-6503-40d1-b927-bc6be86a759b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attendance-widget-btn</value>
      <webElementGuid>b76d86a9-7b90-4d4d-a659-8570501c5808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Resume work   </value>
      <webElementGuid>b2a45959-fdc7-45d5-bce5-fe7616a13c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendance_content&quot;)/a[@class=&quot;attendance-widget-btn&quot;]</value>
      <webElementGuid>153d8297-81fc-4176-ae2d-bc475c10f7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashAttendance/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>dc87041a-6902-46a7-b7fd-82f9954d1367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;markTodayAttendanceOnHomepage('30/01/2024','1002498','R');return false;&quot;]</value>
      <webElementGuid>d0ffebc1-bd7b-4724-b21f-6f2bec3470db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attendance_content']/a</value>
      <webElementGuid>ac6cf52a-2133-421b-8fdc-560063c912c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total hours'])[1]/following::a[1]</value>
      <webElementGuid>0904cbd5-068a-4760-ba7b-71e0f5083276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[2]/following::a[1]</value>
      <webElementGuid>a5ef824d-3772-4107-b694-2e58b3dc1036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>dbb0d16d-c08e-4928-859e-24d2f9abf14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a</value>
      <webElementGuid>ccec7604-7322-4d86-af97-9173dd3e3cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Resume work   ' or . = ' Resume work   ')]</value>
      <webElementGuid>bcd587fc-031b-4991-aaac-e5460fb8796a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
