<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start (1)</name>
   <tag></tag>
   <elementGuidId>4de422fb-1c6e-4314-acbb-4403ba859091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.attendance-widget-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;markTodayAttendanceOnHomepage('30/01/2024', '1002498', 'S');return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aef0b352-0235-4da5-b3c7-df75030d903a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>fe2b98d8-eec3-452c-9c1c-69549dd13e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>markTodayAttendanceOnHomepage('30/01/2024', '1002498', 'S');return false;</value>
      <webElementGuid>e72cf1fa-546c-4073-9573-7dac861f70d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>87ab277b-47be-494d-94ab-0e89dfa5034c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attendance-widget-btn</value>
      <webElementGuid>1eac4a42-b1a7-407a-820a-b186cfae0b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Start    </value>
      <webElementGuid>ecd545bc-f67f-427a-9cd3-0a7a0543b931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendance_content&quot;)/a[@class=&quot;attendance-widget-btn&quot;]</value>
      <webElementGuid>a0df02fe-033f-41b5-849a-4503c981253c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashAttendance/Page_Home page/iframe_Self services_homePageFrame (2) (1)</value>
      <webElementGuid>aea20213-f8e1-4d1b-84ed-9ea7d1c74b19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;markTodayAttendanceOnHomepage('30/01/2024', '1002498', 'S');return false;&quot;]</value>
      <webElementGuid>7c136dfe-5c2e-4f72-aa05-99437da082ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attendance_content']/a</value>
      <webElementGuid>e419f8ea-d5ab-4021-bc86-52ec62240473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total hours'])[1]/following::a[1]</value>
      <webElementGuid>b5556639-fa3d-4aaf-80f5-8078ca379ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[2]/following::a[1]</value>
      <webElementGuid>73f46c93-93cd-425f-b9f4-c8e1cbafdbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>e2e478ae-7b2a-4042-9e57-91b37b2b6f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>fbc71260-01fa-4086-a861-fbcd27002048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a</value>
      <webElementGuid>18f7e0ca-367a-4974-aed9-794188a7e0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @alt = 'Start' and (text() = ' Start    ' or . = ' Start    ')]</value>
      <webElementGuid>927aacba-43d8-46c9-a643-f836c0aa8eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
