<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>d9b62ee1-1b8c-4988-819d-8d16e3079cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b78c49ff-868c-4d79-a377-70341b78a40c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'b78c49ff-868c-4d79-a377-70341b78a40c' and (text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/Empxtrack_DashAttendance/Page_Home page/iframe_Self services_homePageFrame (5)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8d10eb9-c755-4f53-bc80-d0b245c90e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>00894be9-81f8-41e0-9697-82093426a2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b78c49ff-868c-4d79-a377-70341b78a40c</value>
      <webElementGuid>84321387-ffa0-4a8b-9a08-02f25843e8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>19995ee4-7c79-4a59-a4d3-6379e6a95519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b78c49ff-868c-4d79-a377-70341b78a40c&quot;)</value>
      <webElementGuid>e70133ba-ba40-4385-98b6-82fc303306d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashAttendance/Page_Home page/iframe_Self services_homePageFrame (5)</value>
      <webElementGuid>a508e05d-d05c-484f-91b0-8e4303bab986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b78c49ff-868c-4d79-a377-70341b78a40c']</value>
      <webElementGuid>e6a968f4-d315-40df-ad19-cef1d8702560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e4a0b28d-495d-4b05-a01d-7ffb69b15e42']/div/div/div[3]/div/div/button</value>
      <webElementGuid>630ad3d9-41a0-482d-b994-4d4d12cff504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      <webElementGuid>02cb97ab-8354-4db0-9326-dbaf67dd5a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation message'])[1]/following::button[1]</value>
      <webElementGuid>2d3842e3-9f0a-4edc-a0a4-9dd46641cf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>0df71619-a4cb-4395-a76c-6fb3b14311ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'b78c49ff-868c-4d79-a377-70341b78a40c', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>365be041-76e4-4e5f-8f5e-1e59d431bc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>ef23d12e-4330-4279-9086-8f89d5d55d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>67b579cd-ecd1-4012-8c53-da395bcabf91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'b78c49ff-868c-4d79-a377-70341b78a40c' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>cc1f340b-0762-43be-8779-b8146824dbd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
