<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Self services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>88dd3752-b161-460d-b9d2-7e980dfa82c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ac8be896-4b74-454f-bce8-492b42d2e027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D</value>
      <webElementGuid>0ce35b3d-ea29-4c3f-93dd-a639bce0051c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>55e3f4c0-55cf-4f53-bf8b-c0bbb76b0e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>0b81bb29-97bb-405a-b289-9965b9100506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>24f7a898-b29d-43b6-82be-450b459a7cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>ff4530b8-2c42-4871-b0b9-5571ec54ac31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>19aa21cc-a7a3-4e9f-9999-05f6fb844069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>a76ed649-ee3b-4044-b278-00d285d62a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5a5b36b1-5e29-41c2-b826-799cb51bd217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>55a42116-7329-417d-b0a8-66d3cc305012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
