<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Leave Policy</name>
   <tag></tag>
   <elementGuidId>31f41ed8-103e-47ca-b5bf-40f40d098b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:void(0);' and @id = 'secondary_link_showLeavePolicy' and @onclick = concat(&quot;encryptURLForPanel(&quot; , &quot;'&quot; , &quot;mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showLeavePolicy&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'View Leave Policy' or . = 'View Leave Policy') and @ref_element = 'Object Repository/Empxtrack_SSLeave/Page_Home page/iframe_Self services_homePageFrame (1)']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_showLeavePolicy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_showLeavePolicy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>714644fa-3209-4cfb-ac95-87704876e408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>2d179072-b23f-4639-be7c-ba47dc861855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_showLeavePolicy</value>
      <webElementGuid>48978750-fdfd-4cbf-a66a-ad04edc86f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showLeavePolicy')</value>
      <webElementGuid>d413d1e0-a250-4acf-a463-4aadb55815e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>e815e312-aa69-420e-8272-ac493242df5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Leave Policy</value>
      <webElementGuid>b6222079-cd32-482d-861b-140024f9fd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_showLeavePolicy&quot;)</value>
      <webElementGuid>c835cbf0-52fe-491b-b462-1f09ff120ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSLeave/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>3b8dc35d-fc4a-474b-95a7-4df9e4244f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_showLeavePolicy']</value>
      <webElementGuid>ae8a3760-15db-4872-a439-65137398b6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveGroup_getSecondaryLinks']/div[2]/a[3]</value>
      <webElementGuid>ef8793c8-be19-4ec1-bbca-128a3f93954e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Leave Policy')]</value>
      <webElementGuid>1fb89f9c-847f-4e0c-b162-0c29fb094d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Calendar'])[1]/following::a[1]</value>
      <webElementGuid>1d6a5ddf-6a56-43ba-8294-4d22363ad9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave transactions'])[1]/following::a[2]</value>
      <webElementGuid>85f2bbb9-c5b5-4c35-80a3-f1b2185df128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays In-Time'])[1]/preceding::a[1]</value>
      <webElementGuid>6c7548c7-2ad4-492c-9ec5-3912ee2b424e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Leave Policy']/parent::*</value>
      <webElementGuid>563d5aa3-e008-43b2-b508-39c5d7905a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>e965134b-67fb-4612-8785-cf9284868630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>f176d841-afd3-47a7-bf45-8df5761de1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_showLeavePolicy' and (text() = 'View Leave Policy' or . = 'View Leave Policy')]</value>
      <webElementGuid>063dcee8-db2c-41bd-8700-7c17fad07300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
