<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1Days</name>
   <tag></tag>
   <elementGuidId>ed460426-2cd7-4cec-843a-4d38a8236eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#durationCtr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='durationCtr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ada5fdaa-5bf8-4ccd-808c-6b84c8e77ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>durationCtr</value>
      <webElementGuid>638737a4-58a7-4136-91d7-0bd9374c4421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 1 Days</value>
      <webElementGuid>b942e769-f908-4a53-b8b7-1065ed363ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;durationCtr&quot;)</value>
      <webElementGuid>7c686d7c-c8a2-4955-9832-9723cf3ba038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (6)</value>
      <webElementGuid>97b6b433-b52c-49e7-8f0b-372dd32590cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='durationCtr']</value>
      <webElementGuid>53dbb0d8-0f0a-4e64-b519-8ca4115f8b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[5]/div/div/div/div</value>
      <webElementGuid>890ba36e-2c3a-40fb-9d84-4a42b76e6159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 1. Duration'])[1]/following::div[1]</value>
      <webElementGuid>bdb53641-b7f9-432c-950d-40fe0bc0fc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record Updated'])[2]/following::div[8]</value>
      <webElementGuid>baad1f36-68fc-4647-be88-4a2579139c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check one of these boxes if you are taking half day leave'])[1]/preceding::div[4]</value>
      <webElementGuid>0d7ddb72-2dbb-4461-b290-1996cee2cdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div[5]/div/div/div/div</value>
      <webElementGuid>20a6b756-500c-4dca-9f9b-43992a59aea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'durationCtr' and (text() = ' 1 Days' or . = ' 1 Days')]</value>
      <webElementGuid>3c93fb75-25e7-4fd6-852c-684b236ce827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
