<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Apply_fa fa-arrow-circle-right</name>
   <tag></tag>
   <elementGuidId>74a7e43a-7f7e-4848-8031-34c816abb6c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-arrow-circle-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bff02cc3-e47e-43e1-99a6-f6707fb1e9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-arrow-circle-right</value>
      <webElementGuid>b7c83813-bf28-4411-b306-7fa7defb9636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionItems_renderTableHeaderArray_1706511677498_0_0&quot;)/i[@class=&quot;fa fa-arrow-circle-right&quot;]</value>
      <webElementGuid>558bde1c-811b-4c35-bd4b-026773b2a2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>e996352b-0c80-4c3b-a7c1-3dbca53aee61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='actionItems_renderTableHeaderArray_1706511677498_0_0']/i</value>
      <webElementGuid>f250c595-f6a2-4875-9352-0e8d295031a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>2495d8c8-ac4d-4b91-af88-78a3597f7eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
