<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Step 1.Duration_date_dataObject.startDate (2)</name>
   <tag></tag>
   <elementGuidId>b35f23ef-5886-4810-a125-755a37b7fd74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2acf569d-8657-43d8-b5de-abe198a2a7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>77ad71aa-ac34-404a-a6ff-82fc71a39fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d234d96-3711-47d8-b225-0821f418842d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_dataObject.startDate</value>
      <webElementGuid>63dd5d22-faa9-4cbe-acc3-577d6f450589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>556e3966-5168-474c-9d27-241d341ae803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>b514396a-7a98-4492-b585-0473cb80d765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:calculateDays('Yes', '');return false;</value>
      <webElementGuid>0fd75789-1a53-499f-ab3a-cdc6c8f674ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start date</value>
      <webElementGuid>97adb948-e947-4829-820f-b7919afd9ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDate&quot;)</value>
      <webElementGuid>2fc4a524-4c2c-4d1d-a003-335c749c0951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (8)</value>
      <webElementGuid>8aa3ff64-ad16-4871-85b1-6baceed392f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDate']</value>
      <webElementGuid>66d3709d-412f-47b1-be78-246d558ab493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationCtr']/div/input</value>
      <webElementGuid>7cbe4e29-0c85-4f01-b71d-9c719db8f95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>8c9eeaed-cb29-4160-ac99-474bcf7a78a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date_dataObject.startDate' and @id = 'startDate' and @placeholder = 'Start date']</value>
      <webElementGuid>435510ab-c33b-46e1-bea0-8cadd392bb95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
