<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End on first-half of 3101_dataObject.secondHalf</name>
   <tag></tag>
   <elementGuidId>3b25cef3-1803-43c7-b844-728391244ef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;secondHalf&quot;)[count(. | //*[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox' and @onclick = concat(&quot;javascript:calculateDaysOnCheckBox(&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;);return true;&quot;) and @ref_element = 'Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (4)']) = count(//*[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox' and @onclick = concat(&quot;javascript:calculateDaysOnCheckBox(&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;);return true;&quot;) and @ref_element = 'Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (4)'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#secondHalf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondHalf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>621a3efb-913d-4b8e-870c-c7fc463b7481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.secondHalf</value>
      <webElementGuid>eb3deae2-134a-40f2-ad90-be085a547851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5928e0b-e589-4119-8764-2ab6cc5651b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondHalf</value>
      <webElementGuid>46073d1e-96eb-44ac-9424-b78f2b9f0ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>762d7777-36ee-42ef-b93c-79786d1b8de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>18fba5ec-6d8e-4650-9a1f-46ac75b37235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondHalf&quot;)</value>
      <webElementGuid>dbda4b8e-1be1-452c-9e7c-1379aa35e97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (4)</value>
      <webElementGuid>d5cf34d1-a6c2-4bff-909b-002af964e156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondHalf']</value>
      <webElementGuid>a5b4fcc1-dbe3-4afe-bdd0-c7097c23afc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div[2]/label/input</value>
      <webElementGuid>a53afd2c-b053-4b26-8d1e-ae5feebf999e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>18aee662-4d4a-4cbc-8656-a8588ac0458f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox']</value>
      <webElementGuid>5be03483-83a8-4efc-9170-13ed0edd5a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
