<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Toggle Dropdown Apply</name>
   <tag></tag>
   <elementGuidId>d5bf8e3d-2bd6-428b-8db7-3a7463b95c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick=&quot;javascript:event.cancelBubble=true;showDropDownInRenderTable('renderTableHeaderArray_1706511677498', '0'); return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>eabc8149-526e-4da9-a38d-50804a4d6e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>b9d441ef-4325-42a0-8735-d19ae05da3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:event.cancelBubble=true;showDropDownInRenderTable('renderTableHeaderArray_1706511677498', '0'); return false;</value>
      <webElementGuid>79d2b464-7672-4d21-805b-00c15e8dc68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Toggle Dropdown Apply </value>
      <webElementGuid>0765478b-8209-4d69-9d17-0c4c2174e49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renderTableHeaderArray&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>3f5b72cb-63e9-410e-bfc5-b57dde48709b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>85116e03-9991-479c-9963-6cd034162864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;javascript:event.cancelBubble=true;showDropDownInRenderTable('renderTableHeaderArray_1706511677498', '0'); return false;&quot;]</value>
      <webElementGuid>a3192ee7-4ac4-45ef-8d10-028cbc4d379b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='renderTableHeaderArray']/tbody/tr/td[3]</value>
      <webElementGuid>0fc61e67-55df-45d0-9dfa-39962160ffd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casual Leave'])[1]/following::td[2]</value>
      <webElementGuid>241c475c-d9ac-4bbc-a696-8ca835ac467f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::td[3]</value>
      <webElementGuid>1e788fcf-d0b0-4062-913b-2b4018893406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>cb91872b-c282-42e2-af73-7ce9f0ab88fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Toggle Dropdown Apply ' or . = ' Toggle Dropdown Apply ')]</value>
      <webElementGuid>1bea6c97-c736-4497-b639-3a255bdde3e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
