<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Step 2.Specify a reason for the le_ccdaad</name>
   <tag></tag>
   <elementGuidId>0144d72e-b63e-4991-9f6a-e00462f47e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reasonForLeave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reasonForLeave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ad97cc8f-961e-49fa-8657-2cc7842e3e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>26ade49b-7e53-4328-863c-cc8e692cf455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.reasonForLeave</value>
      <webElementGuid>3d67ee18-24d5-4991-8de8-78809828f56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>textLimit(this, 1000);</value>
      <webElementGuid>227ebace-94a5-41a6-acdf-ffbb81344d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reasonForLeave</value>
      <webElementGuid>0e4f2322-dba7-45f8-8662-42a9d36b7738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reason for leave</value>
      <webElementGuid>c3fcb972-ea51-44fc-b740-7e8786af0a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reasonForLeave&quot;)</value>
      <webElementGuid>8913c141-494d-4809-85ab-2293dc4c31dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame (6)</value>
      <webElementGuid>207fa5eb-f52d-47c1-bcca-e8edaad42d37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reasonForLeave']</value>
      <webElementGuid>5e29bca7-344a-4835-b03e-b74741d1ceed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[5]/div/div[3]/textarea</value>
      <webElementGuid>415cf230-9f71-4df6-84bd-fb2962212143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2c9dbbbf-d49a-4e58-8de5-962bd6542800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'dataObject.reasonForLeave' and @id = 'reasonForLeave' and @placeholder = 'Reason for leave']</value>
      <webElementGuid>01f3d9a4-722d-478d-a6b0-642181e4ddfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
