<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Reason</name>
   <tag></tag>
   <elementGuidId>f4a0c2a4-71e7-4863-bac7-43c62e910602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reasonForLeave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reasonForLeave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>72ee8cdf-e480-4592-a897-0ec99b6e7701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>10a123d8-2acf-41bb-88d6-4e27cb3680d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.reasonForLeave</value>
      <webElementGuid>2563fb36-1fe7-437b-bb98-5fd49a5805b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>textLimit(this, 1000);</value>
      <webElementGuid>613c1d31-0f83-4a60-943d-7eceb90e02f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reasonForLeave</value>
      <webElementGuid>f46a8bf1-707a-403a-a9d2-794bb0c79719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reason for leave</value>
      <webElementGuid>b5e47cc3-00ff-4288-a450-1baa2f0526b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reasonForLeave&quot;)</value>
      <webElementGuid>803aba9b-026a-4097-b98c-b4f4e89417a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_DashLeave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>529b9459-dc39-47f2-9d85-112ead3252fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reasonForLeave']</value>
      <webElementGuid>50694dba-d9a6-4487-819c-af9404232a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[5]/div/div[3]/textarea</value>
      <webElementGuid>a18d57ce-cbed-4eb7-b1ba-50bd406a3df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6d8c8caf-23f8-4071-a124-001b932f1d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'dataObject.reasonForLeave' and @id = 'reasonForLeave' and @placeholder = 'Reason for leave']</value>
      <webElementGuid>b834d6bd-438a-458d-b9da-b9d923a30c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
