<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chat</name>
   <tag></tag>
   <elementGuidId>a83da509-9589-4ffd-a32c-a52344f1e022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-warning.li_gray_default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;showHidePanel_v9('allChatItems');showChatMessageBox_v9();return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33fb9c50-8db2-4d1b-a269-7b775064a80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>1c618311-b8f1-4e89-b4e2-65f774d98979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning li_gray_default</value>
      <webElementGuid>6f9e31ae-4311-4e7e-b3d6-fa4f675fadce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHidePanel_v9('allChatItems');showChatMessageBox_v9();return false;</value>
      <webElementGuid>1d02d9ca-0c7e-4f5f-93c4-8850b3ce223d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chat</value>
      <webElementGuid>7175607e-7710-4aa3-914e-1861120eb7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allChatItems&quot;)/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;chat-widget&quot;]/div[1]/a[@class=&quot;btn btn-warning li_gray_default&quot;]</value>
      <webElementGuid>766da06f-082d-448e-a255-381055c2b060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;showHidePanel_v9('allChatItems');showChatMessageBox_v9();return false;&quot;]</value>
      <webElementGuid>2738c78e-1c91-476e-b3be-5aaf434d8948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allChatItems']/div/div/div/a</value>
      <webElementGuid>631e45d8-2ac0-4d50-b1a0-412170a62b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Chat')]</value>
      <webElementGuid>2da144e6-6c70-4bfe-b658-1377399175b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communicate'])[1]/following::a[1]</value>
      <webElementGuid>63d64012-7ead-472c-9c7d-cee220bfac86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::a[1]</value>
      <webElementGuid>7bc5d0f7-b2aa-43b4-932f-92046d634ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chat']/parent::*</value>
      <webElementGuid>fc7e9bee-a164-4a55-85d6-d6048c04ab28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>979f5303-0f2b-4506-bb94-8601978e64bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/a</value>
      <webElementGuid>a10bf612-5f81-40f1-874f-0a8d8d6e30f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Chat' or . = 'Chat')]</value>
      <webElementGuid>e06eed09-c3f0-4741-b1ab-75c504fed5b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
