<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thanks for submitting the feedback</name>
   <tag></tag>
   <elementGuidId>c8521275-6be1-4cb4-b6b6-9ce73dc828a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#48fbb57f-f553-429a-a7c5-e444536b3921 > div.modal-dialog > div.modal-content > div.modal-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2648570-2dd3-432d-bead-888da2854870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>211df88c-5627-4ee2-b987-7e51c8d237ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanks for submitting the feedback.</value>
      <webElementGuid>c69f6e31-2f07-481d-bcf5-e29f9c3505f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;48fbb57f-f553-429a-a7c5-e444536b3921&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]</value>
      <webElementGuid>655d6c29-6379-4430-ab81-3fed423a528f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='48fbb57f-f553-429a-a7c5-e444536b3921']/div/div/div[2]</value>
      <webElementGuid>5bd12289-833e-4c0f-a9d9-4cabbd76df5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::div[1]</value>
      <webElementGuid>eaff7305-abf0-44c1-8f57-9a9c84e051a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/following::div[2]</value>
      <webElementGuid>26c141a7-9886-4676-94f1-6f33d00dda55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::div[3]</value>
      <webElementGuid>cc81eeb1-d11a-4d92-8741-f2c560008162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]</value>
      <webElementGuid>7c8cab40-fd48-4a79-8602-f3ab67b3a3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thanks for submitting the feedback.' or . = 'Thanks for submitting the feedback.')]</value>
      <webElementGuid>023232c2-340f-4fb3-abf3-882503b5cefb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
