<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp  10 (1)</name>
   <tag></tag>
   <elementGuidId>14eae875-4ece-4de7-8e92-ef0ba0fe94b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1004825</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1004825']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>308a52ab-d1ad-462d-9495-4416f7a2ac2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1004825</value>
      <webElementGuid>aab87d9b-5e17-4134-b758-9f606621655a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>9215c82e-8427-4699-9b8a-318421d54c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp  10 </value>
      <webElementGuid>dad7c6d7-491c-4ddb-8c61-2197cb4b3909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1004825&quot;)</value>
      <webElementGuid>36c55fe8-3e36-42dc-a9d1-6c99f49f5425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1004825']</value>
      <webElementGuid>f381a249-8016-4d90-ae24-9eda69c70467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>0e3f12a2-241a-4d8c-8a67-d64c4c44bbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[7]/following::div[2]</value>
      <webElementGuid>b7180397-8736-41a1-a852-4a54a6dd8ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::div[10]</value>
      <webElementGuid>b901a107-0c4e-482d-b965-8ee2a46f6a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>b79cbd4e-73ee-49ae-a408-c7fb417cfd12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>b115307d-8052-4650-9dff-f5ff2ab0ac8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>9f13867a-0813-460b-b33a-0eb57dd7b56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1004825' and (text() = 'emp  10 ' or . = 'emp  10 ')]</value>
      <webElementGuid>e3184c5b-06a0-4de7-80ca-249b0e5565d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
