<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Message centerHelp</name>
   <tag></tag>
   <elementGuidId>4781c59c-2c45-4f2e-a51e-45b891a6702f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show_hide_page_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show_hide_page_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b3b2576-7a1a-4131-b042-52f69f6231f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 headerbar</value>
      <webElementGuid>17ac5593-beb3-42e9-acab-1152e8961819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_hide_page_title</value>
      <webElementGuid>212021d5-7f2e-49f4-93a6-222313ea5dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Message center  Help×</value>
      <webElementGuid>ee48b6e9-b905-4295-962b-aaaeea0faca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_hide_page_title&quot;)</value>
      <webElementGuid>ac1060b0-f383-4307-a00d-9583b3432921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='show_hide_page_title']</value>
      <webElementGuid>4633409c-80fb-4feb-b7ed-0ac26f9a5022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/div</value>
      <webElementGuid>15fa04e5-9963-42c3-9a9a-da1119d41845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[2]/following::div[8]</value>
      <webElementGuid>f37055eb-e2a0-48bb-bfc4-180eb3a499b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[2]/following::div[11]</value>
      <webElementGuid>3eab546c-d0a2-4935-a3f7-cc0339d0ab0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div</value>
      <webElementGuid>e1777bff-1f36-4fe8-a731-366ef9eae323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'show_hide_page_title' and (text() = 'Message center  Help×' or . = 'Message center  Help×')]</value>
      <webElementGuid>bd7ecd8c-62de-4110-ba4b-87dd057ec2e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
