<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp  10</name>
   <tag></tag>
   <elementGuidId>ecd4cff6-1fa3-403b-a596-eed5c0afaaca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1004825</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1004825']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00824bbb-4f17-40e0-95bd-66c3a7aa89d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1004825</value>
      <webElementGuid>2d25b832-fa36-4401-a183-523c659cc1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>4f3508d2-e8d2-46d9-b168-88b27e6c914b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp  10 </value>
      <webElementGuid>5846b9dc-1d92-424a-b063-1188b6274aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1004825&quot;)</value>
      <webElementGuid>d7bb7f13-1154-48d9-86db-c777be719ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1004825']</value>
      <webElementGuid>0d7e7e21-ab40-4af0-8423-68c65a817843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>3c93c8f9-fbb0-45b2-b57d-90381eb263a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '1004825', '&quot;', ')')])[1]/following::div[3]</value>
      <webElementGuid>2ac2b3ea-cdc6-40ad-851b-d0022ab00aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>1551993e-1ef8-4323-85c9-b1e30167f92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>2da5a7c7-5e21-45d9-9f7d-ca3d7af15549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1004825' and (text() = 'emp  10 ' or . = 'emp  10 ')]</value>
      <webElementGuid>49d48e35-88c8-4188-9379-a53c879e637a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
