<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Notifications (.as Employee)</name>
   <tag></tag>
   <elementGuidId>501289b8-9523-47ff-8e64-3d41ae6f6cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notificationItems']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>7de95e22-9d1d-41a4-a779-b6302005daef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notifications (...as Employee)</value>
      <webElementGuid>57b2e977-ff5c-491d-91a7-406777aed558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notificationItems&quot;)/h3[1]</value>
      <webElementGuid>eb8c6350-68ec-4bd0-b8b1-b1b3557ddb8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notificationItems']/h3</value>
      <webElementGuid>55838063-59ef-4e79-a00d-4e0ad3c8c908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::h3[1]</value>
      <webElementGuid>4c8d542b-e063-4456-b5c2-1a6fb6db6dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No new notifications. You are on top of everything!'])[1]/preceding::h3[1]</value>
      <webElementGuid>f4c2b45e-803c-4418-9fc5-d7b4d88c9e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>198be8e7-860a-4748-ac5f-ade269cb73a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Notifications (...as Employee)' or . = 'Notifications (...as Employee)')]</value>
      <webElementGuid>b5ca453e-a200-4115-9f52-7a1a0575d828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
