<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Time based activities</name>
   <tag></tag>
   <elementGuidId>23a3ab72-9f60-4b1e-a736-d53e289c20ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#allTimeItems > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allTimeItems']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6e7989b4-b888-49d7-9895-1f224d857ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time based activities</value>
      <webElementGuid>b01706ca-d3be-4c6c-9327-71efbfcba4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allTimeItems&quot;)/h3[1]</value>
      <webElementGuid>f66e0b46-37f0-47a7-a7a8-5da97508287d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allTimeItems']/h3</value>
      <webElementGuid>23808765-9dbf-4f1e-9b98-b06fbd8395a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[2]/following::h3[1]</value>
      <webElementGuid>a06c74bb-dfda-40c3-a1c3-14ff6049757b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[1]/preceding::h3[1]</value>
      <webElementGuid>a0fba8ff-15cf-4240-8f33-7b90d2c30ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/h3</value>
      <webElementGuid>4b5e789c-b483-44da-b229-49ab93f13adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Time based activities' or . = 'Time based activities')]</value>
      <webElementGuid>3e27b441-d259-412f-be1d-6b57542aeb75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
