<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_chat</name>
   <tag></tag>
   <elementGuidId>225e8afa-1f0b-4d68-921c-0943a36cfbb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chatItems123 > a.pull-right > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chatItems123']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a083ebde-5757-471d-9011-0cb1f86cd06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/v10/chat.png</value>
      <webElementGuid>8543a45e-c67c-47f3-b7f0-ef6c4715ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chatItems123&quot;)/a[@class=&quot;pull-right&quot;]/img[1]</value>
      <webElementGuid>80c33bf7-d542-417f-8675-9313f20205aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chatItems123']/a/img</value>
      <webElementGuid>e9cbf2fc-665f-4b8c-801a-5938403653df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>d901d463-449e-4991-b324-723a4506dc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/v10/chat.png']</value>
      <webElementGuid>748771b7-ba45-41a6-b859-fba16c18a882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
