<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_notification</name>
   <tag></tag>
   <elementGuidId>b1218fcc-0ee5-4382-803e-7c1cf616527e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notificationItems123 > a.pull-right > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notificationItems123']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc277ecc-8f5a-401e-a461-3562fe783584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/v10/notification.png</value>
      <webElementGuid>8c00991c-82b2-4bdb-8ec8-664df84152c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notificationItems123&quot;)/a[@class=&quot;pull-right&quot;]/img[1]</value>
      <webElementGuid>f2659fe6-5d99-43f7-bb21-f325f2ac7773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notificationItems123']/a/img</value>
      <webElementGuid>38ee5047-f241-4cba-846e-84198c4c2f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>a0a8bb37-074d-46c0-a45e-36e1817a121f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/v10/notification.png']</value>
      <webElementGuid>5c8915a8-cbb1-43a3-8a99-913f7774cc13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
