<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating_pulseRating_4</name>
   <tag></tag>
   <elementGuidId>78e65a37-91cd-44e2-aaec-6d93fb8444d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9daae477-d07b-4465-a3c9-69e5fa21be78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/blankStarRating.gif</value>
      <webElementGuid>c3089e55-dddd-4a7b-a04c-5d42f1b546eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>5.0</value>
      <webElementGuid>ade0cb24-5ae6-4a39-b1d9-8ac62e1912c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_4</value>
      <webElementGuid>58248aeb-916f-4aff-9266-d3e3aba8b099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','4','5','5.0');setChanged();</value>
      <webElementGuid>d36f1629-6093-4021-b777-f87bce77242b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_4&quot;)</value>
      <webElementGuid>abe4877a-8d48-4085-97d5-1c50fae0e40e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_4']</value>
      <webElementGuid>9963dc70-d41b-4049-ad65-148833cc0b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img[5]</value>
      <webElementGuid>0fc25782-fdf4-4daa-8b10-4344a0e70078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='5.0']</value>
      <webElementGuid>e2be21b0-6dac-4166-98e9-1084f8b132ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[5]</value>
      <webElementGuid>b961768e-d480-4f7f-a6ea-521fd4757714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/blankStarRating.gif' and @title = '5.0' and @id = 'pulseRating_4']</value>
      <webElementGuid>e0e711ad-4e70-4daf-b8b3-943c26c6cc51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
