<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Share a suggestion_empxtrack_feedback_subject_by_client</name>
   <tag></tag>
   <elementGuidId>bcd32a79-4676-4748-be33-a53bf50b3b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_subject_by_client</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>871f5ce8-2e2e-43f1-a7e3-c4beee072758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>796a684f-abf6-499a-8cb4-8a12a845746c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_subject_by_client</value>
      <webElementGuid>fd77b8c8-09a5-4036-9239-45a393be8830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>efca9bac-b5a3-4d6c-beea-1701a2df53e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Specify area</value>
      <webElementGuid>0fdc5a76-9241-4b9e-9f9d-24ebf69f661c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_subject_by_client&quot;)</value>
      <webElementGuid>05821eec-0ce0-4d04-a248-0f4aafd0cf41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      <webElementGuid>7d1d8605-a289-47f6-8374-228c551e8166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>ec08d6e1-80e6-4001-93ee-0a6aeb3e74cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>04135527-1c08-435e-850a-df7a3b7fb494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'empxtrack_feedback_subject_by_client' and @type = 'text' and @placeholder = 'Specify area']</value>
      <webElementGuid>89625c36-ab89-458e-8174-c4fac6d06038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
