<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Check for anonymous submit_checkAnonymousSubmit</name>
   <tag></tag>
   <elementGuidId>49fb3559-bdbd-4e6c-b8f4-24300c5dcdac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkAnonymousSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkAnonymousSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed2a3728-c5b7-4451-bf96-d16d1c6a6886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7fb0c3b0-e6ce-4e22-9dd0-fa727fe873dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkAnonymousSubmit</value>
      <webElementGuid>9f293a7d-424c-4117-9518-a6a59749e276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkAnonymousSubmit</value>
      <webElementGuid>31938925-dcec-417e-96e4-9aaf58c7e6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkAnonymousSubmit&quot;)</value>
      <webElementGuid>06ac5b21-b626-42ee-818c-2eebc3688284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkAnonymousSubmit']</value>
      <webElementGuid>f103af5e-a13c-46fa-8fe6-e119a0d1bfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[3]/label/input</value>
      <webElementGuid>f99b8c9a-bc7a-48d7-a1da-4b3a17b92d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>722abc1d-73c8-48b4-bceb-21085c8db469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkAnonymousSubmit' and @id = 'checkAnonymousSubmit']</value>
      <webElementGuid>ec385aca-e7a1-45ec-ae1e-3af77418447b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
