<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Share a suggestion_empxtrack_feedback_by_client</name>
   <tag></tag>
   <elementGuidId>090b2c89-020e-4098-af1a-5b94667c9ca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_by_client</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a032a6da-5d42-4ec3-8a4f-af0af7f9f1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a040949-959f-4aaf-9a1f-98716496bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_by_client</value>
      <webElementGuid>acc55956-eba3-4286-b876-12e134d94dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your suggestion</value>
      <webElementGuid>9b83c114-1fb5-4b03-aad9-1dd6c828d7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_by_client&quot;)</value>
      <webElementGuid>32255a28-3d77-4501-be74-d7b8d20f3b50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      <webElementGuid>c0c60980-f0c0-4cb8-af1f-025fff2210fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>1f941ec6-a79c-4ea8-a505-4a5e19ac2677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>86f1f66e-d5ed-4cd9-8f49-2ee85ca34cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'empxtrack_feedback_by_client' and @placeholder = 'Your suggestion']</value>
      <webElementGuid>ff6cad29-d41d-4f03-8c88-4c6ff6a165be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
