<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_chatMessageContent</name>
   <tag></tag>
   <elementGuidId>082f9ee9-1118-4ee3-86a1-3e3a7d8c9b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chatMessageContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='chatMessageContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1ed615b9-a2f5-4758-b027-544d65df3689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chatMessageContent</value>
      <webElementGuid>cdd8ebd2-80bd-432a-b136-edc99640b142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f46ff9db-c361-4593-81b1-50e99afffeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3b9c620a-d0e9-4b51-8785-83b9fff9174f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b21866f8-becb-4ef6-b8ce-cc725ff6a5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chatMessageContent&quot;)</value>
      <webElementGuid>3439e468-8238-4e88-920a-a97aa769f4c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='chatMessageContent']</value>
      <webElementGuid>52807e99-8385-4c41-96c1-275f6ba0a4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[4]/textarea</value>
      <webElementGuid>ae28167e-3f3d-45cd-a25c-277c2ccfba52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9f06b970-6c68-474e-ab89-99a7dfc3a25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'chatMessageContent']</value>
      <webElementGuid>eea4f81d-84b2-4310-8679-30b3594c139d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
