<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hobbies (1)</name>
   <tag></tag>
   <elementGuidId>bff52c49-08bd-4a24-bf20-694bcb3d6b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;btn_3&quot;)[count(. | //a[@id = 'btn_3' and @onclick = concat(&quot;javascript:triggerPersonalDataModes(&quot; , &quot;'&quot; , &quot;AddButtonEmpHobbiesInterestsMethod&quot; , &quot;'&quot; , &quot;);return false;&quot;) and (text() = 'Hobbies ' or . = 'Hobbies ') and @ref_element = 'Object Repository/Empxtrack_Profile/Page_Home page/iframe__mycontent-right-frame (2)']) = count(//a[@id = 'btn_3' and @onclick = concat(&quot;javascript:triggerPersonalDataModes(&quot; , &quot;'&quot; , &quot;AddButtonEmpHobbiesInterestsMethod&quot; , &quot;'&quot; , &quot;);return false;&quot;) and (text() = 'Hobbies ' or . = 'Hobbies ') and @ref_element = 'Object Repository/Empxtrack_Profile/Page_Home page/iframe__mycontent-right-frame (2)'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8feb626b-d71d-4833-a080-091d5d71647a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_3</value>
      <webElementGuid>57a92a68-42e5-4caa-b30b-42668879dfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:triggerPersonalDataModes('AddButtonEmpHobbiesInterestsMethod');return false;</value>
      <webElementGuid>1ad8f37c-679a-453d-9589-be80a09964d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hobbies </value>
      <webElementGuid>0a6e064e-d0f5-40ea-a49c-e57e6be76218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_3&quot;)</value>
      <webElementGuid>b4a6d1af-7d06-4ee3-991e-5dac68fe1a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Profile/Page_Home page/iframe__mycontent-right-frame (2)</value>
      <webElementGuid>fdc993c3-cba6-4609-9737-83f5e1fd1b6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_3']</value>
      <webElementGuid>357e8308-d152-4c50-be95-88289ee43ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalDetailsDiv']/div/div/div/div[3]/div[4]/a</value>
      <webElementGuid>186e799f-2bbe-4b3d-9c86-49e658010721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hobbies')]</value>
      <webElementGuid>d0c8be43-b1fb-4894-af73-cdc62072a522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other details'])[1]/following::a[1]</value>
      <webElementGuid>57ea77a3-7ac1-420b-8dd0-08d950d5513d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiaries'])[2]/following::a[2]</value>
      <webElementGuid>99fb26aa-07ec-4a8a-a743-c58653c073a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages known'])[2]/preceding::a[1]</value>
      <webElementGuid>3b138ef9-fbde-42b0-b884-880bdc3bb255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact details'])[1]/preceding::a[2]</value>
      <webElementGuid>110d4ce0-6c7e-4fdd-b289-f44587cd213a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>66a4ecd0-f4ba-4f88-80b8-8bf50c678751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_3' and (text() = 'Hobbies ' or . = 'Hobbies ')]</value>
      <webElementGuid>1acc671c-02a9-46d0-9c74-39a5e9c327ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
