<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp 04Help</name>
   <tag></tag>
   <elementGuidId>2a1c0f10-36ec-4816-b721-6435a6f70add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show_hide_page_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show_hide_page_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>356fc7b3-4784-4653-bfeb-8e868c061dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 headerbar</value>
      <webElementGuid>e5c81991-2463-4747-8081-61e22295f218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_hide_page_title</value>
      <webElementGuid>1acfc170-e171-41d1-b0d2-1a57a7cf60cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp 04  Help×</value>
      <webElementGuid>4090bb60-45f2-4f47-b505-fa2042a25394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_hide_page_title&quot;)</value>
      <webElementGuid>07feac22-b49a-4e4c-8dc0-86855284db84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='show_hide_page_title']</value>
      <webElementGuid>87d0e9d5-796f-4ade-aa6a-fb7adfad6a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/div</value>
      <webElementGuid>2a64b7da-2e66-41d7-8e8f-a0bf6183823c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::div[8]</value>
      <webElementGuid>85604898-f0ad-459a-9c38-19347e29d7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[11]</value>
      <webElementGuid>4fa17ed0-0e17-4fa4-9018-18769c387e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div</value>
      <webElementGuid>cb916335-4cef-415d-9ed6-177be01ec9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'show_hide_page_title' and (text() = 'emp 04  Help×' or . = 'emp 04  Help×')]</value>
      <webElementGuid>c11edc80-42a7-44e2-8b6a-d2b461c7e271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
