<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Self services</name>
   <tag></tag>
   <elementGuidId>8fd86ece-af3f-494d-87ce-b683c066494b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5f09195-aafa-4d2e-b663-6fa4f018dcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transact</value>
      <webElementGuid>c94c78c1-0e61-4b0f-ad46-82ec4d909705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10-side-menu-item</value>
      <webElementGuid>d5b89c21-e864-452e-ac0b-089cc9b7fd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayURL( 'runet.do?activity=submit&amp;mod=transact');return false;</value>
      <webElementGuid>a17b8dbb-4e07-468e-8275-96bb0335e373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self services</value>
      <webElementGuid>16689e3a-ad1e-4b14-aeba-c210dfc2ab5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transact&quot;)</value>
      <webElementGuid>d1e36dd2-1ab5-4742-a55f-f0ebc107dff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='transact']</value>
      <webElementGuid>cae68830-82c4-416f-a4ec-d3c2a8a694e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left_side_menus']/div/div[2]</value>
      <webElementGuid>c993ee81-afe6-420e-90e7-c336ff2e3bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[1]</value>
      <webElementGuid>18ec07a6-7ec5-4b46-aafb-d20895f800f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log off'])[1]/following::div[7]</value>
      <webElementGuid>fc5da0c7-75ba-40cd-b4dd-828f0cbfc125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::div[35]</value>
      <webElementGuid>63e34da2-0725-4ec1-a4df-d3ebc768ca02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>51817afe-c4e2-49e6-8ae4-15bd0dd9c644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'transact' and (text() = 'Self services' or . = 'Self services')]</value>
      <webElementGuid>abb6b2f3-7c3b-4892-b69d-f7b036377fe3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
