<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame (3)</name>
   <tag></tag>
   <elementGuidId>c073c992-b7d0-4c35-82f7-b3e5c6b279d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d6401c7d-16ff-43bb-8c3b-5f96a2d48ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=mEpD%2F5b%2FNBT2iXfZ5vACXIBSG3NeoKURQsQUQ4V6weNmqGY5k34QOxHObQYa92LmzB98Onui6%2FWu%2FZThjMCgaASa5bFS7fw+&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>d7c5973b-6301-4ea4-b8b9-dfdd2ae87c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>35d4d076-0003-47ca-a2af-afab1b8e01c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>7b40e7f2-bd59-4f42-a9a6-3e8f351ada5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>88c7056f-0467-412d-a08e-affabc2131a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d38b9e84-8f10-4dfc-9ee0-8cc05b33081f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>441a364d-81e2-4c39-8ec7-97e1114cb729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>2848058f-47bf-479e-8cb0-b6ec98404ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>4b023fbe-e1bc-4d61-b8ab-c22fde62e745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>9a463ce0-8e93-4d4b-b415-7939a4896574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>34711c71-e826-42ee-b821-131a12b4a9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=mEpD%2F5b%2FNBT2iXfZ5vACXIBSG3NeoKURQsQUQ4V6weNmqGY5k34QOxHObQYa92LmzB98Onui6%2FWu%2FZThjMCgaASa5bFS7fw+&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>2dbc6358-1551-41c8-98f9-d2228fd1806c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
