<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame</name>
   <tag></tag>
   <elementGuidId>d5ba101b-57f1-4310-bd81-d434efc9da7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4cb19e45-0c63-426b-a0c3-293eeedba57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=mEpD%2F5b%2FNBT2iXfZ5vACXIBSG3NeoKURQsQUQ4V6weNmqGY5k34QOxHObQYa92LmzB98Onui6%2FWu%2FZThjMCgaASa5bFS7fw+&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>df89cfee-0475-448e-baaa-79529eee1d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>cc351dae-8131-4072-a293-f79156740235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>4cbc946e-fe66-4e14-9e88-4dcaf1dcbc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>6168b485-14b6-4abc-9d22-d4d1b3b35472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8920717f-9a10-4485-a413-19a2684122d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>2ead14b5-8afc-4823-ace8-3aed0e98e067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>7a543ec2-c2a2-41d1-91e3-d724a8880bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>d364f513-9fb8-47af-a6ee-40164a89bd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>3ed16f4e-291f-48a0-9888-9640efd89503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>8d1d2073-3643-43ef-907a-5cc02d8e75a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=mEpD%2F5b%2FNBT2iXfZ5vACXIBSG3NeoKURQsQUQ4V6weNmqGY5k34QOxHObQYa92LmzB98Onui6%2FWu%2FZThjMCgaASa5bFS7fw+&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>1698a9a7-81cf-479d-aa0b-9199e4179d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
