<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame (4)</name>
   <tag></tag>
   <elementGuidId>cf8ccc1d-efc8-43d3-9151-2bb224ae61c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>27822537-89d3-46ce-92f0-64315295b9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=mEpD%2F5b%2FNBT2iXfZ5vACXIBSG3NeoKURQsQUQ4V6weNmqGY5k34QOxHObQYa92LmzB98Onui6%2FWu%2FZThjMCgaASa5bFS7fw+&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>df5eef0c-761b-4bf9-a1f6-77017e260042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>98ec4a3e-5c57-422b-9a6d-e7f40a866145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>9349e884-3852-41a3-80c7-19196d42dd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>0030277e-a3f1-41c5-925c-1e823259a20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>234dec27-3fed-4983-9ac6-fcdb71dd5674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>d662a81a-4ff3-4a32-bf64-ccdbb0a1ed87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>6857e471-8a4e-4961-8f32-c78758d6972d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>69c6d89c-e26f-4b35-889e-a15a93d46887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>35b49118-4bed-4ddb-942f-11fa738ddd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>346500f8-2624-4ac3-8dab-aaf92bd48b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=mEpD%2F5b%2FNBT2iXfZ5vACXIBSG3NeoKURQsQUQ4V6weNmqGY5k34QOxHObQYa92LmzB98Onui6%2FWu%2FZThjMCgaASa5bFS7fw+&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>2bd475f7-132e-404a-8003-eba0ff5f3dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
