<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Hobbies  Interests_hobbies0</name>
   <tag></tag>
   <elementGuidId>34e7b122-8c9d-4a5b-ab00-08d8b6cefdcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbies0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div[2]/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9caa3c5c-655c-4a19-9857-847b70b4df67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e39cf3ca-02a2-46d5-b90c-eb2538a1ae03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f8adbfb8-0200-4895-9418-ec76faabc935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies0</value>
      <webElementGuid>528620c0-b61e-4431-a1b4-e0f292eeb786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>numericFilter(this);return false;</value>
      <webElementGuid>6eab1c73-919f-4fb5-adc7-5ea24bf24d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies0&quot;)</value>
      <webElementGuid>e08399f4-1bab-4f8d-8323-288d405bb35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Profile/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>4929dd15-1417-4e1a-b15f-8795cdabc902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies0']</value>
      <webElementGuid>8aa0d2a7-560b-4230-88f7-daa89f45f910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a1767735-4c77-4ad6-8417-13b433beaac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>23676c9e-8b4e-45ae-8eda-18255da2fda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hobbies0']</value>
      <webElementGuid>ad600810-f6f5-4f9b-a68e-2c8786f049c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
