<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Hobbies  Interests_hobbies0 (1)</name>
   <tag></tag>
   <elementGuidId>c4f743bc-4033-4f01-b266-11982b8c1fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hobbies0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hobbies0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c78ac848-69fd-463c-93ac-82c5e0d79337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ac7fb81-1c28-41e9-99ee-597b456cdae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6621bfb6-7b50-4e02-8716-214ab82ba487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies0</value>
      <webElementGuid>9787bbca-8114-46c6-ae4f-713106b94f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>numericFilter(this);return false;</value>
      <webElementGuid>fc66c86d-7c5a-4fce-82e9-7db833e9b7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies0&quot;)</value>
      <webElementGuid>98b79f7e-ac45-431c-80c6-2bd7a9ea46f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Profile/Page_Home page/iframe__mycontent-right-frame (3)</value>
      <webElementGuid>8a4adc35-fe9c-46fc-aa5f-393f9403fe56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies0']</value>
      <webElementGuid>1c9dc548-6944-4d6d-b4bb-c69072cc5d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>569a458d-8bdb-4c43-a5f0-58f1abfef7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>5eb16df5-518e-4afe-8bc2-3521e5239051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hobbies0']</value>
      <webElementGuid>3a49187b-778e-4bea-8c64-18fa991d8e3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
