<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View all changes to my data</name>
   <tag></tag>
   <elementGuidId>0ef69f91-81db-4438-9c4a-f3cc3e9157ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='modal-header-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-header-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbf6d1a3-1d9c-4679-892e-b987e8e6ff73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-header-title</value>
      <webElementGuid>375ace94-aee3-401c-b890-ac95018de4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View all changes to my data</value>
      <webElementGuid>54f4f0c8-0e27-415a-a7cc-2f6e10945554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-dialog-empxtrack&quot;)/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@id=&quot;modal-header-id&quot;]/span[@id=&quot;modal-header-title&quot;]</value>
      <webElementGuid>953a9538-5b13-4683-abec-d06790b2c282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Profile/Page_Home page/iframe__mycontent-right-frame (5)</value>
      <webElementGuid>676e5e57-f8e8-41d4-8481-1e1cf1ba620f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='modal-header-title']</value>
      <webElementGuid>9c01eba8-abb3-4e20-b2da-19bb3cdf1b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-header-id']/span</value>
      <webElementGuid>4257c39a-7d36-487c-9c71-403425f644cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in full page'])[1]/following::span[1]</value>
      <webElementGuid>436a7004-3448-42ab-95ff-2d49716a1125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[3]/following::span[1]</value>
      <webElementGuid>438ea64a-b013-44c9-9827-e01f041a38ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section'])[1]/preceding::span[2]</value>
      <webElementGuid>86c0c42d-9df0-4330-9d65-682fb8f1e8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initiated by'])[1]/preceding::span[2]</value>
      <webElementGuid>a1ec479a-cb47-41ea-9b2f-be9b3f04ae4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View all changes to my data']/parent::*</value>
      <webElementGuid>66facdcf-81ee-4b09-b973-f213962cd367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span</value>
      <webElementGuid>ec52955d-7057-4957-8c2b-05e49d22ca2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'modal-header-title' and (text() = 'View all changes to my data' or . = 'View all changes to my data')]</value>
      <webElementGuid>5d549154-b26b-44f4-8bc9-225c8b9df580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
