<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_e</name>
   <tag></tag>
   <elementGuidId>6ccdc398-baeb-49a7-b5fd-fb8e010bba5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profileImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profileImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>526fa840-2628-42f5-a937-697da101a2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profileImage</value>
      <webElementGuid>ba2e77dc-2362-4f60-9135-a82b900db65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profileImage</value>
      <webElementGuid>ff8da319-eee5-46bd-a745-5b954553e791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>e</value>
      <webElementGuid>9f9e80ff-747f-4bf0-b413-b76133850e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileImage&quot;)</value>
      <webElementGuid>4ce4e85a-ccb5-493a-8b56-4e4e9ebc113c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profileImage']</value>
      <webElementGuid>eb21ebbc-b277-472a-b7f2-4041448ba33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdownMenu1']/div</value>
      <webElementGuid>2e140304-f7f9-4437-9c4a-7088165104d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::div[3]</value>
      <webElementGuid>06a73e4b-88d5-4096-8015-28171f2f5e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 04'])[1]/following::div[4]</value>
      <webElementGuid>3b214e92-6fd5-4790-b615-d9cf23eeaaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 04'])[2]/preceding::div[4]</value>
      <webElementGuid>95621ff5-0bf4-4670-a22f-67ced06f5279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>a025daef-dac5-4ab4-9caa-a990c05be6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profileImage' and (text() = 'e' or . = 'e')]</value>
      <webElementGuid>41f70008-4c3f-4e55-bb86-1ae0fa6ab9b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
