<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp 04Default  Default</name>
   <tag></tag>
   <elementGuidId>dd5e3986-b950-4c71-b40b-249921a2a1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.emp-des</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section_user_bar']/div/div[2]/ul/li/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39d3af25-c78e-4342-ab23-d24631825c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emp-des</value>
      <webElementGuid>46569651-6558-4723-8634-c35dad072fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp 04Default | Default</value>
      <webElementGuid>0de3ddaf-ef1c-4ea5-831d-928353105876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section_user_bar&quot;)/div[@class=&quot;col-md-12 toprightN&quot;]/div[@class=&quot;col-md-4 col-xs-5 pull-right dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/div[@class=&quot;emp-des&quot;]</value>
      <webElementGuid>b394ca5f-bf1a-4753-88db-80dd2e87a251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section_user_bar']/div/div[2]/ul/li/div[2]</value>
      <webElementGuid>026b6ecb-49e1-4d07-9a0c-1eb844dc2ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e'])[1]/following::div[3]</value>
      <webElementGuid>7360780c-546d-4dd2-af03-5269aeb14124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::div[7]</value>
      <webElementGuid>493beb0d-9649-49cb-86a5-cb55e9f9468f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div[2]</value>
      <webElementGuid>47300ec3-9ffe-4d90-807c-2e882ff82c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'emp 04Default | Default' or . = 'emp 04Default | Default')]</value>
      <webElementGuid>e5a062aa-6f80-4f2d-888b-a25d007ee810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
