<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_cpassword</name>
   <tag></tag>
   <elementGuidId>c7706b70-09c1-4256-aa02-5ac0265f4265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1c41ee7-c496-4877-aeea-57bd67337dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8ff84fff-0a2d-4cee-ba21-9d240bfa47dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpassword</value>
      <webElementGuid>24d168df-aa44-4ea7-af15-98f7c7b7c820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>edfc89f9-afc7-49aa-b528-5832ab296a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpassword&quot;)</value>
      <webElementGuid>889c3fba-d434-4916-9220-5de2fbfa7a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Profile_Icon/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>8efb6a76-6e97-48db-908f-70fc3454c50a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpassword']</value>
      <webElementGuid>c7a7256e-b3b8-4f73-a38c-9910eab184ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div[5]/div[3]/div/input</value>
      <webElementGuid>2d0039cf-3251-4da6-81d6-ad4a624ea9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>322c03b5-6e66-4253-8ff1-472432156bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'cpassword']</value>
      <webElementGuid>60857802-cddd-4d1b-ba55-b529e1a30267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
