<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Old password_oldPassword</name>
   <tag></tag>
   <elementGuidId>e791cf5b-cadc-4f9d-8279-ad4713433cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oldPassword</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;oldPassword&quot;)[count(. | //input[@type = 'password' and @id = 'oldPassword' and @class = 'form-control' and @ref_element = 'Object Repository/Empxtrack_Profile_Icon/Page_Home page/iframe__mycontent-right-frame']) = count(//input[@type = 'password' and @id = 'oldPassword' and @class = 'form-control' and @ref_element = 'Object Repository/Empxtrack_Profile_Icon/Page_Home page/iframe__mycontent-right-frame'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a10881f-c25e-43cb-8fac-11e37776a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3b1beec3-e369-4221-b6ef-6f3241bab3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldPassword</value>
      <webElementGuid>b4ada727-df14-43a5-b314-133dab54e84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>687ecab6-e382-4233-824c-f3c500093173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldPassword&quot;)</value>
      <webElementGuid>6e050549-cc5b-49e4-8e3a-3bd9295cab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Profile_Icon/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>7636db2d-cf17-48b8-82bf-ee16649ee160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldPassword']</value>
      <webElementGuid>7749d4c8-d2a5-44a9-bfa9-7bceff07fafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div[5]/div/div/input</value>
      <webElementGuid>a854de12-05b8-4309-ae42-c57bcf002376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>3ebda989-1a61-45f4-b7f9-8d7b3db32c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'oldPassword']</value>
      <webElementGuid>9f7b3ae0-8f50-4ba2-8cab-d8781ac77772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
