<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>15bed7ec-cd6b-45c1-b949-c39c900ea0df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4f96c7d3-f775-417e-b84d-475d8877e8ac</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='4f96c7d3-f775-417e-b84d-475d8877e8ac']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f23a249-d337-42af-8433-ee21161df101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>b7d1a3da-07d4-4c12-b26f-455295050c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4f96c7d3-f775-417e-b84d-475d8877e8ac</value>
      <webElementGuid>70327824-90f4-482e-9ce4-837e64a1f56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>917abc06-2e24-4a8f-aeba-7cbabceff3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4f96c7d3-f775-417e-b84d-475d8877e8ac&quot;)</value>
      <webElementGuid>d4b06542-cc58-4874-9c90-3783e219911b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Feed/Page_Home page/iframe_Self services_homePageFrame (5)</value>
      <webElementGuid>3af54beb-8bdf-436a-b958-5a0d78ab3816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='4f96c7d3-f775-417e-b84d-475d8877e8ac']</value>
      <webElementGuid>64eb1af2-ec67-4607-9d00-3dfab138e964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9b286e0c-dcd2-4c2d-a4b5-60f526f19c26']/div/div/div[3]/div/div/button</value>
      <webElementGuid>1b433f53-e5ba-4759-83b9-ebf23f582819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the comment'])[1]/following::button[1]</value>
      <webElementGuid>22f17bff-22d7-43ca-b7d8-edf1662c192d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>36542b6d-572a-45d1-bb9f-7b14f2be781d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '4f96c7d3-f775-417e-b84d-475d8877e8ac', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>55267c7f-c386-43b5-b0b6-995abd449ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>f4850f54-e657-435a-8804-e9c78376811a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>57c98f82-f85a-4d0d-91ed-d9da3b0bd194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '4f96c7d3-f775-417e-b84d-475d8877e8ac' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>4b715842-8aba-4041-a3b5-70a8ff38222b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
