<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__master_overlay_tempt</name>
   <tag></tag>
   <elementGuidId>cae3d9ce-971c-4861-a24a-a0950a4f70e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.master_overlay_tempt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myProfileView1']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1c07dc9-47c0-4bdc-9602-54b2bdfa2fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>master_overlay_tempt</value>
      <webElementGuid>e4851e0c-034c-4230-bf78-cb668de9fdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myProfileView1&quot;)/div[@class=&quot;col-md-12 master_profile-tempt&quot;]/div[@class=&quot;master_overlay_tempt&quot;]</value>
      <webElementGuid>8095a627-0f50-464c-8bcd-a5083dcd00a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Feed/Page_Home page/iframe_Manager services_homePageFrame</value>
      <webElementGuid>ed475834-fabb-4952-be65-5ec0d2c3bb91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myProfileView1']/div/div</value>
      <webElementGuid>9bca2ebd-9737-4a5d-a5f3-61d1c843fc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/div[2]/div/div/div</value>
      <webElementGuid>a6938c78-f092-44cd-9bad-ea689aa8f201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
