<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_emp 10_fas fa-ellipsis-v</name>
   <tag></tag>
   <elementGuidId>7159573d-a748-43e9-a3e2-17f70a070c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-ellipsis-v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buddy_box_1000012']/div/div[3]/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>77fe0e23-34db-4f25-921e-f44512cb4873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-ellipsis-v</value>
      <webElementGuid>b1d47a95-1947-4ab2-b8f4-c43cab67767b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buddy_box_1000012&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-3 col-xs-3 buddy-action pull-right&quot;]/span[1]/i[@class=&quot;fas fa-ellipsis-v&quot;]</value>
      <webElementGuid>cd4bd4d0-5036-4a62-8489-7bcd84bd9f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Feed/Page_Home page/iframe_Self services_homePageFrame (6)</value>
      <webElementGuid>b89be8ca-3121-4f21-9dd5-a5decdf4b2f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000012']/div/div[3]/span/i</value>
      <webElementGuid>25d8a4a5-8d89-45f3-891d-9fd0deb208a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/i</value>
      <webElementGuid>8f9d4c62-0e7a-49d1-8e89-f871c68270bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
