<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Say hello to emp 10 on joining  as Defaul_35f1c0</name>
   <tag></tag>
   <elementGuidId>904ed28b-446e-4ce0-9076-1f409c439b06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-paper-plane</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='jsFunUpdate_-1']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>93d4104a-b926-4cc1-821b-b55c759176e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-paper-plane</value>
      <webElementGuid>9b29d1ed-893d-45c0-b21e-a7f7536f6e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buddy_box_1000012&quot;)/div[@class=&quot;col-md-12 comment-box&quot;]/div[@class=&quot;col-md-3&quot;]/a[@id=&quot;jsFunUpdate_-1&quot;]/i[@class=&quot;fa fa-paper-plane&quot;]</value>
      <webElementGuid>1913b0d2-2225-4ff6-9af7-3468d8836c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Feed/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>9c53c34b-f44a-4c95-b2e8-8fb642845d0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='jsFunUpdate_-1']/i</value>
      <webElementGuid>fc5f054d-96af-435f-9cec-5cf207cc348c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/a/i</value>
      <webElementGuid>98d0be26-a4da-4e7b-9cfa-e9d28cf0fb7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
