<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Say hello to emp 10 on joining  as Default_fontCls_1000012</name>
   <tag></tag>
   <elementGuidId>7ad9faa1-ccfb-4a75-9370-d08e81938c95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fontCls_1000012</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='fontCls_1000012']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>85eb47be-0d6f-4646-8082-a11fb992262c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fontCls_1000012</value>
      <webElementGuid>e5ceebd8-dc07-4bef-bb0e-8d048380a6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-thumbs-up likefeed</value>
      <webElementGuid>b99f944a-f56c-4cb7-8e76-33b465f5f4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fontCls_1000012&quot;)</value>
      <webElementGuid>d247833a-99e0-464a-b796-4641de8f27b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Feed/Page_Home page/iframe_Self services_homePageFrame (4)</value>
      <webElementGuid>e4e196ec-81f8-4628-aefd-578e0e34baba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='fontCls_1000012']</value>
      <webElementGuid>a0b27a08-33fe-4c7e-b2e4-816d48e86fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='jsFunUpdate_1000012']/i</value>
      <webElementGuid>ddaf4485-66ad-44af-ace9-eb9819ee3729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a/i</value>
      <webElementGuid>b2edf01d-aacf-452d-a81b-19ab32a7008d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'fontCls_1000012']</value>
      <webElementGuid>14d74ebd-900c-4cd3-b23f-d02c22a5633e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
