<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame</name>
   <tag></tag>
   <elementGuidId>1a967edc-77ee-4d2e-bb78-f803e9c2fb41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c429f6ce-23bf-427e-b28b-7da57f0f9fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>83030ce6-d255-4c89-a024-17adef808595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>01d39b27-2023-4b45-ac4f-6a09f47e1ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>cc038471-612d-4ec1-a424-19806da82942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>63d5d6a1-13a7-4c64-999d-820cc793703b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4df0e428-1cdc-4aa0-b7f1-b9cb68418885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>dca32729-8558-47eb-850c-f7670d643a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>7e731f13-938b-423b-841c-3267f24259d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>cb1a342e-7058-4e10-b289-551bf7660a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>53d4c6e6-ed36-48e1-8116-efc5ce9c7a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>09cef6cb-742d-4ceb-bd67-d3e0588b16bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>b7c124af-ca40-4a9a-aa3b-fe1972426cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
