<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Manager services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>230de859-8776-4b4d-8562-ad8ea4d64248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>366f7129-1dcf-44d1-9132-b11fa8abb0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHT7XIl8hsJFEMoT5xKz7rWCmm98XBirJGaMYtbEkBoSra8p0bqpWijYx9okq%2FKQ7WsJyBT9oQ1O+sJGJR7NcsOm8D5hwi8WTeVuj772PwqrT3d0VCO2uHEh</value>
      <webElementGuid>1e187b83-ab35-4eaf-8783-727559d9a2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>816c8f2d-2df1-4deb-b636-58f95fbcee14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>5eecd9fc-c6b3-4dd6-bf37-d612596824ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>49fa0236-9a80-4114-9bca-2e31ede9bde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>ecd63783-ce0f-4e61-881e-0dc9ab265bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>1f8ad3f3-918a-4915-842e-64cffa0205c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>945d0f97-2b64-4e4d-a4fe-7f23cdffd768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2c2ee052-1189-45e4-ab4f-0c38d428b1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHT7XIl8hsJFEMoT5xKz7rWCmm98XBirJGaMYtbEkBoSra8p0bqpWijYx9okq%2FKQ7WsJyBT9oQ1O+sJGJR7NcsOm8D5hwi8WTeVuj772PwqrT3d0VCO2uHEh' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>c3d60c57-437d-4054-aee7-a22533391eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
