<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Say hello to emp 10 on joining  as De_b8626a</name>
   <tag></tag>
   <elementGuidId>a18f5110-2eb3-4b11-a2f9-e2a9b42baaeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_reponse_note_1000012</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_reponse_note_1000012']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>871326dc-1ccf-45f7-80b5-9f6916ea57ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dce1ebb-d212-4a1c-87a7-90b84c49468a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_reponse_note_1000012</value>
      <webElementGuid>38df7c83-c8cd-485c-9670-ac1c5004c133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e01a196-abb9-45f9-a258-5da5a5e70718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment</value>
      <webElementGuid>278cf820-88d1-47de-b106-7018deb7d411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_reponse_note_1000012&quot;)</value>
      <webElementGuid>ff468bc8-1fef-41e2-84d0-7cfbe8aa6ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_Feed/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>705a3016-6f16-48f6-824c-4e6f13084f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_reponse_note_1000012']</value>
      <webElementGuid>052f88bf-e9af-4c36-91ac-692b737f0c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000012']/div[8]/div/div/input</value>
      <webElementGuid>b1e0d14e-8040-4e9a-b733-ab3c70409dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>f2db8b15-7350-43c6-85fd-c59dc88d20a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_reponse_note_1000012' and @placeholder = 'Enter your comment']</value>
      <webElementGuid>515c6c22-1dbf-418a-89d7-06e3c3fcde0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
