<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Minus(1)</name>
   <tag></tag>
   <elementGuidId>f342b1d7-b9e6-442a-80e6-a9505ccc74b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='removeRowMyAttendance(this.parentNode.parentNode);'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7af2270f-770c-4bf4-943c-a5f0584734f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>8c8f2af2-e8c8-4757-8f98-6f0550e218d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>removeRowMyAttendance(this.parentNode.parentNode);</value>
      <webElementGuid>caffe76f-5d13-4024-9237-080d64739072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breakTable&quot;)/tbody[1]/tr[2]/td[3]/a[2]</value>
      <webElementGuid>81764294-2e83-43d2-ac18-373c54958ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSAttendance/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>a3801c75-caf4-42ad-8b35-f2749993c6ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='removeRowMyAttendance(this.parentNode.parentNode);'])[2]</value>
      <webElementGuid>4dc72770-d600-4018-ac9c-3adacd9505be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='breakTable']/tbody/tr[2]/td[3]/a[2]</value>
      <webElementGuid>bbffcd56-4294-426a-8a98-5980f9b150cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In time:'])[2]/following::a[2]</value>
      <webElementGuid>9ad502af-6964-4b5d-9ad7-b3ab73771907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Out time:'])[2]/following::a[2]</value>
      <webElementGuid>75cb875c-9e37-4234-b9d0-47a002f04fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculated time'])[1]/preceding::a[1]</value>
      <webElementGuid>c7b842c9-3392-46d7-a1b3-6692702a1591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hours'])[1]/preceding::a[1]</value>
      <webElementGuid>cd94fb2c-2bd0-4e34-8b79-84e7b0d990cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[5]</value>
      <webElementGuid>4a2eb20c-c688-47ae-a3fa-5ad05d70181e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a[2]</value>
      <webElementGuid>4897709a-6e29-4845-a3a9-cda5c44899f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;']</value>
      <webElementGuid>dbbd1852-4d30-4df1-a8c6-e44e9a5125ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
