<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Minus</name>
   <tag></tag>
   <elementGuidId>0650ba5d-e655-4ebf-a2be-8de39740a913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='removeRowMyAttendance(this.parentNode.parentNode);'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81e4dd1f-1b58-46bf-917e-650362aa0ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>33a333a2-30e7-45d7-a581-6e0ab8f97589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>removeRowMyAttendance(this.parentNode.parentNode);</value>
      <webElementGuid>3b943943-c2ec-4657-8254-04feebc6ee6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breakTable&quot;)/tbody[1]/tr[2]/td[3]/a[2]</value>
      <webElementGuid>de70d7b8-4d97-4eef-8640-a3ed2af5b967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>8a023673-9200-490c-950f-d2461c9216cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='removeRowMyAttendance(this.parentNode.parentNode);'])[2]</value>
      <webElementGuid>a37afea3-eb1e-4a20-973e-38ed796ae3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='breakTable']/tbody/tr[2]/td[3]/a[2]</value>
      <webElementGuid>ca9ab7e2-e584-4110-81d8-d72c029e8f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In time:'])[2]/following::a[2]</value>
      <webElementGuid>a090d5f2-7368-426a-a264-b22f4e64d892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Out time:'])[2]/following::a[2]</value>
      <webElementGuid>c4c29ee8-2fa3-4370-94aa-a9861f49bdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculated time'])[1]/preceding::a[1]</value>
      <webElementGuid>cf54e7c9-c347-4c26-b8ae-3b68c7c6bbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hours'])[1]/preceding::a[1]</value>
      <webElementGuid>d32d4de4-06e4-4f97-aa1e-76258d1c9d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[5]</value>
      <webElementGuid>2bc63c61-3d6a-4480-8b8a-eed857ba3431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a[2]</value>
      <webElementGuid>8f75bcd4-6872-4c78-b4d3-c73530496432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;']</value>
      <webElementGuid>84c5b2d6-b4de-4e0a-b31a-f725054c5220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
