<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Out time_outTime</name>
   <tag></tag>
   <elementGuidId>7f6298b3-438a-4444-bc41-4bd6fbcfec72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dab0518-5d66-487a-8e53-3ce5f0598631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control timeText hasDatepicker</value>
      <webElementGuid>c1faeb9f-cd51-4364-913d-109321d49658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>289039c1-e0b5-45f8-96b5-7cee0cd81fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outTime</value>
      <webElementGuid>3e57e3db-c30c-4f9d-9bb3-4fba0b43cc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateHrs();</value>
      <webElementGuid>10f61abe-3b92-4d75-bc8e-499ebfdf6247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03:07</value>
      <webElementGuid>52b1c089-2d83-46ae-acff-d3401a7e9bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8cc3dd11-1ad9-45c1-9d46-ea54e8f8a1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outTime&quot;)</value>
      <webElementGuid>6a45ccdc-4eb4-4aaf-9794-8f03e3427904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>2bcbafdd-e672-4f06-9baf-33300798cb32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outTime']</value>
      <webElementGuid>62065c2a-086f-4a5c-923f-2b6fab222d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[3]/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>b1799fd2-9d11-44dc-9a9b-986da0706a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>e423e8f1-cd32-426b-9cd4-0d1c2f870172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'outTime']</value>
      <webElementGuid>33743bce-a0a8-4a30-a669-c5c1ebf2c86b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
