<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_In time_inTime</name>
   <tag></tag>
   <elementGuidId>94d1b142-0d96-4e75-ad3e-d7e111831c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inTime']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;inTime&quot;)[count(. | //*[@class = 'form-control timeText hasDatepicker' and @type = 'text' and @id = 'inTime' and @onchange = 'calculateHrs(); ' and @ref_element = 'Object Repository/Empxtrack_SSAttendance/Page_Home page/iframe_Self services_homePageFrame']) = count(//*[@class = 'form-control timeText hasDatepicker' and @type = 'text' and @id = 'inTime' and @onchange = 'calculateHrs(); ' and @ref_element = 'Object Repository/Empxtrack_SSAttendance/Page_Home page/iframe_Self services_homePageFrame'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77dc16c5-4459-42fc-a11e-d97e513e5de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control timeText hasDatepicker</value>
      <webElementGuid>695a9b79-0fa0-4a90-aa6d-ef7ad186a5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>296857b7-5e01-48ad-a9b9-b2a74a957058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inTime</value>
      <webElementGuid>faf3d0c4-fe68-43ce-b36a-ebb43b87b9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateHrs(); </value>
      <webElementGuid>8cf59a2a-c587-4ce0-9760-94b4735a3bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>02:52</value>
      <webElementGuid>8011e7e3-eb2f-4d7e-bb06-b609d7c75f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>103c73ca-f15f-4814-a42e-83eb8840660e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inTime&quot;)</value>
      <webElementGuid>0b334b24-3210-45f4-9e6b-ddd41c837cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>4462ae86-5801-41bb-98e2-b7f822e939aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inTime']</value>
      <webElementGuid>983bcc35-4656-4b1a-b6e6-91908b9823fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[3]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>79e1a900-9a43-4809-ad2f-b8549483d5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>b7578f4b-45f5-4639-8fa0-5187619dda4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inTime']</value>
      <webElementGuid>169045f0-cbe8-48aa-b33f-396afc2254ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
