<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_0_commonNotesData</name>
   <tag></tag>
   <elementGuidId>e8049ed2-9dcd-453f-863e-ddc1fe9faea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commonNotesData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='commonNotesData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bcc3a2f0-b4d8-42dd-9311-c2cdf7c426ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control expanding-textarea</value>
      <webElementGuid>3e09dc74-663e-46a4-99aa-00e58ea618aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commonNotesData</value>
      <webElementGuid>bc4215db-13eb-4252-9112-5161f53865a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commonNotesData</value>
      <webElementGuid>9f246551-d127-4b8c-b8c2-e485b8f3453e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write a comment...</value>
      <webElementGuid>b049a2a1-8b6f-4c26-8ef9-46495117e10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commonNotesData&quot;)</value>
      <webElementGuid>aa04e306-97a5-48e6-94f1-ec1f4e0e97de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack_SSAttendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>f0516f6e-161a-4f9d-bc91-15a5d21d59e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='commonNotesData']</value>
      <webElementGuid>f7e232a3-5357-45e1-8a9d-47c570b51ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noteBoxId']/textarea</value>
      <webElementGuid>a6bd0a1d-d923-4f16-80ab-71569ce432af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6e4d1b2e-ae60-4dd0-9974-8e9455ac407a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'commonNotesData' and @name = 'commonNotesData' and @placeholder = 'Write a comment...']</value>
      <webElementGuid>671ccc42-283b-4822-933a-a3109e39a115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
